dracut-ng/dracut-ng

.github/workflows/container.yml
.github/workflows/integration.yml
.github/workflows/manualtest.yml
README.md
docs/HACKING.md
man/dracut-catimages.8.asc
man/dracut.8.asc
man/lsinitrd.1.asc

This change is required to initialize CI for dracut-ng.

chore: rename dracutdevs/dracut to dracut-ng/dracut-ng

---

test/container/Dockerfile-Gentoo

systemd-utils can now install kernel-install independently of systemd-boot, but systemd-boot requires that option to be enabled.
Fixes: https://github.com/dracutdevs/dracut/issues/2554
(Cherry-picked commit from dracutdevs/dracut#2562)

ci: adapt Dockerfile-Gentoo for recent systemd-utils change

---

modules.d/95resume/module-setup.sh

Since https://github.com/systemd/systemd/commit/a628d933, the generator only does the initial validation of the system info and then enables the new `systemd-hibernate-resume.service`.
Fixes https://github.com/dracutdevs/dracut/issues/2513
(Cherry-picked commit from dracutdevs/dracut#2527)

fix(resume): add new systemd-hibernate-resume.service

---

modules.d/90kernel-modules/module-setup.sh

The MacBook Pro 2017 (MacBookPro14,1) connects the keyboard via SPI:
```
$ dmesg
input: Apple SPI Keyboard as /devices/pci0000:00/0000:00:1e.3/pxa2xx-spi.3/spi_master/spi2/spi-APP000D:00/input/input4
```
The SPI controller requires the `intel_lpss_pci` kernel module:
```
$ lspci -vv
00:1e.3 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO SPI Controller #1 (rev 21)
Subsystem: Intel Corporation Sunrise Point-LP Serial IO SPI Controller
Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
Latency: 0, Cache Line Size: 256 bytes
Interrupt: pin D routed to IRQ 23
Region 0: Memory at 9282c000 (64-bit, non-prefetchable) …
```

fix(90kernel-modules): add intel_lpss_pci for MacBook Pro 2017

---

modules.d/90kernel-modules/module-setup.sh

The x13s, and possibly other Qualcomm based devices need the QC IPC router driver in order to enable USB. Without it, its not possible to boot from USB-C attached disks.
IPC in this case is Inter _Processor_ Communication and forms the message bus used to communicate between differing processing elements in a given system/SoC running and managing various hardware devices. This means that while it appears this driver should be in the dracut network modules that is incorrect because its not for enabling host networking in the initrd, but rather for communicating with other hardware blocks.
Those other blocks aren't limited to modems, but any SMD (shared memory device), which on QC based machines includes the audio DSPs, RPM (resource power manager) and of course the application processor …

feat(kernel-modules): add Qualcomm IPC router to enable USB

---

modules.d/90kernel-modules/module-setup.sh

MediaTek's PCIe (pcie-mediatek-gen3) and the PHY driver depends on `spmi-mtk-pmif` which is related to power domain. Power domain relate driver `spmi-mtk-pmif` must be included in the initramfs for supporting PCIe if user want to access peripherals during boot, for example, NVMe disks.
So install all System Power Management Interface (SPMI) modules on ARM/RISC-V.
Bug-openSUSE: https://bugzilla.suse.com/show_bug.cgi?id=1216767
Bug-Ubuntu: https://launchpad.net/bugs/2038512
(Cherry-picked commit from dracutdevs/dracut#2557)

feat(kernel-modules): Install SPMI modules on ARM/RISC-V

---

modules.d/91pcsc/module-setup.sh
modules.d/91pcsc/pcscd.service

On Fedora, and possibly others, there is a file to load the module opensc-pkcs11.so.
In my tests, without this module, you can't unlock a LUKS encrypted volume using a smart card since pscsd is not able to establish any communication with it.
The file simply loads opensc-pkcs11.so with the following syntax:
module: opensc-pkcs11.so
There may be a more efficient way of doing this without having to attempt to add the file from various sources (each distro seems to have this file in different places).
This pull request adds the installation statements needed to include the file that loads opensc-pkcs11.so on various distributions. I couldn't find where this file lives in Arch Linux. Maybe it's loaded in the configuration directly.
(Cherry-picked commit from dracutdevs/dracut#2547)

fix(pcsc): add opensc load module file

---

.github/workflows/integration.yml

20 seems to be unstable and running a very long time. Once the CI is green, we will revisit this test.

ci: disable test 20

---

test/container/Dockerfile-OpenSuse-latest

openSUSE blacklisted ntfs3.
This PR should make test 16 green for openSUSE, but since this is a CI container change it will only take effect in subsequent PRs (this is just how CI is setup for now).
Fixes https://github.com/dracut-ng/dracut-ng/issues/28
CC @mwilck @aafeijoo-suse

ci: remove mkfs.ntfs from openSUSE test containers

---

dracut.sh

This file was added in https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/amd-ucode/README?id=89ec6198f13d1007563ff87aae5de209e993be07 and it should be skipped.
Fixes [#2541](https://github.com/dracutdevs/dracut/issues/2541)
(Cherry-picked commit from dracutdevs/dracut#2544)

fix(dracut.sh): skip README for AMD microcode generation

---

modules.d/01systemd-pcrphase/module-setup.sh

The binary systemd-pcrphase was renamed to systemd-pcrextend in systemd 255, but the backing units were all left named systemd-pcrphase.
Fixes: [#2583](https://github.com/dracutdevs/dracut/issues/2583)
(Cherry-picked commit from dracutdevs/dracut#2610)
Received positive feedback from @dtardon

fix(systemd-255): handle systemd-pcr{phase -> extend} rename

---

modules.d/10i18n/module-setup.sh

handle keymaps that are symlinks to others, for example:
KEYMAP=de-nodeadkeys in vconsole.conf is:
lrwxrwxrwx 1 root root 20 17. Mai 2023  /usr/share/kbd/keymaps/xkb/de-nodeadkeys.map.gz -> at-nodeadkeys.map.gz
(Cherry-picked commit from dracutdevs/dracut#2613)

fix(i18n): handle symlinked keymap

---

test/TEST-62-SKIPCPIO/test.sh

This test is always being skipped.
Fixes https://github.com/dracutdevs/dracut/commit/4235c03
Fixes regression introduced by 4235c03
(Cherry-picked commit from dracutdevs/dracut#2486)

fix(TEST-62-SKIPCPIO): test always skipped due to buggy `test_check`

---

test/TEST-18-UEFI/test-init.sh
test/TEST-18-UEFI/test.sh

identify the boot drive by id
This should fix the TEST-18 failure on openSUSE for the CI.
(Cherry-picked commit from dracutdevs/dracut#2565)

test(UEFI): make test determinsitic

---

Makefile
docs/HACKING.md
test/Makefile
test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-OpenSuse-latest
test/test-functions

Remove sudo from test containers.
After fd9cd02, tests no longer requires to be root. Being able to run VMs to run tests is required, but that should not imply root user.
Fixes [#1147](https://github.com/dracutdevs/dracut/issues/1147) and https://bugs.gentoo.org/298014
(Cherry-picked commit from dracutdevs/dracut#2429)
Received positive signals from @thesamesam, @Flowdalic and @bdrung .
Ubuntu has been carrying this PR - https://changelogs.ubuntu.com/changelogs/pool/main/d/dracut/dracut_060+5-1ubuntu2/changelog

fix(test): running tests no longer requires to be root

---

test/container/Dockerfile-OpenSuse-latest

The way multipath works in SUSE distros differs from upstream, causing some tests to fail.
This reverts commit c08ae406bc7c7d815b0911d9429f400719afc2ae.
Fixes https://github.com/dracutdevs/dracut/commit/c08ae406
(Cherry-picked commit from dracutdevs/dracut#2499)
This should make tests 3,13,14 green for openSUSE, but since this is a CI container change it will only take effect in subsequent PRs (this is just how CI is setup for now).

revert(ci): install multipath-tools into openSUSE container

---

test/container/Dockerfile-Debian

Improve the Debian container:
The dash package is a required that must be present on all Debian systems.
The debhelper and quilt packages are only needed for packaging dracut.
To make the list of required packages more architecture independent, replace qemu-system-x86 by qemu-kvm in the Debian Docker image.
(Cherry-picked commit from dracutdevs/dracut#2491)

ci: remove unused packages from Debian container

---

.github/workflows/integration.yml

Changes the job name from
"Integration Test / test (arch:latest, 10)" to
"Integration Test / 10 on arch".
This change makes the job names shorter and more readable.
(Cherry-picked commit from dracutdevs/dracut#2385)

ci: improve the redability of job names

---

modules.d/45ifcfg/module-setup.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh

The `45ifcfg` module should be considered deprecated now since ifcfg files themselves are deprecated. They've been replaced by e.g. NetworkManager keyfiles or systemd-networkd files.
Currently, the `45ifcfg` module checks if the `/etc/sysconfig/network- scripts` directory exists to know if to automatically get pulled in. However, on systems with NetworkManager, this directory always exists even if the functionality to read ifcfg files is disabled by default (NM kindly ships a README in there to ease migrating to keyfiles).
Since almost everyone should've already migrated to a more modern alternative, let's make this module purely opt-in now.
(Cherry-picked commit from dracutdevs/dracut#2529)
This model is removed in some of the distro packaging already (such as Arch or Debian)
CC @pvalena …

fix(45ifcfg): mark as deprecated and strictly opt-in

---

test/container/Dockerfile-Arch
test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-Gentoo
test/container/Dockerfile-OpenSuse-latest
test/container/Dockerfile-Ubuntu

These Dockerfiles are only used in the context of this repo, no need to point back to the github url.
This should help finalizing repo url changes and the churn in test containers.

ci: drop maintainer entry from container descriptor files

---

.github/workflows/integration.yml

openSUSE has been actively maintaining network-legacy dracut module.
Fedora is no longer packaging network-legacy dracut module ([Remove network-legacy module](https://src.fedoraproject.org/rpms/dracut/c/a1ebaf27b616010bc672be9409ff42b8234b008d)), so it is not a good container to test the network-legacy dracut module.
CC @aafeijoo-suse

ci: run legacy network tests on openSUSE instead of Fedora

---

tools/test-github.sh

Remove test infrastructure code that no longer runs and no longer used.
(Cherry-picked commit from dracutdevs/dracut#2209)

test: remove dead code regarding building rpm

---

man/dracut.cmdline.7.asc
modules.d/98dracut-systemd/dracut-cmdline.sh
modules.d/98dracut-systemd/dracut-initqueue.sh
modules.d/98dracut-systemd/dracut-mount.sh
modules.d/98dracut-systemd/dracut-pre-mount.sh
modules.d/98dracut-systemd/dracut-pre-pivot.sh
modules.d/98dracut-systemd/dracut-pre-trigger.sh
modules.d/98dracut-systemd/dracut-pre-udev.sh
modules.d/99base/init.sh
modules.d/99shutdown/shutdown.sh
src/util/util.c

Since the introduction of the `dracut-util` binary to parse kernel command line arguments, if the user inputs multiple `rd.break=` options, dracut only stops the boot process at the last one.
```
[    0.985362] localhost dracut-cmdline[245]: /bin/dracut-cmdline@18(): info 'Using kernel command line parameters:' ' ... rd.debug rd.break=cmdline rd.break=pre-pivot'
...
[    1.044979] localhost dracut-cmdline[245]: /bin/dracut-cmdline@48(): getarg rd.break=cmdline -d rdbreak=cmdline
[    1.044979] localhost dracut-cmdline[245]: /lib/dracut-lib.sh@155(getarg): debug_off
[    1.044979] localhost dracut-cmdline[245]: /lib/dracut-lib.sh@23(debug_off): set +x
[    1.044979] localhost dracut-cmdline[245]: /lib/dracut-lib.sh@218(getarg): return 1
```
For options that can be specified multiple times, …

fix(dracut): correct regression with multiple rd.break= options

---

.github/CODEOWNERS

All CODEOWNERS are automatically added as reviewers. This should help new contributors to discover from whom to get reviews.
I hope to add more people soon. This is only a start.

chore(github): update CODEOWNERS file

---

modules.d/90overlayfs/module-setup.sh
test/TEST-20-NFS/client-init.sh

Check for overlay kernel module support.
Execute mount-overlayfs later in the boot process. Without this change dracut  -a "overlayfs nfs" does not work as expected.
(Cherry-picked commit from dracutdevs/dracut#2269)
Received positive review from @aafeijoo-suse .

fix(overlayfs): allow hostonly and nfs support 

---

test/TEST-10-RAID/finished-false.sh
test/TEST-10-RAID/hard-off.sh
test/TEST-10-RAID/test.sh

Same as [#2011](https://github.com/dracutdevs/dracut/pull/2011) but for test 10.
This PR is a refactor, it should not change how the test is executed.
(Cherry-picked commit from dracutdevs/dracut#2238)

test(RAID): make test 10 use the test dracut modules

---

man/dracut.cmdline.7.asc
modules.d/90dmsquash-live/dmsquash-live-root.sh

This change is required to make the following canonical example work that is mentioned in the [documentation](https://github.com/dracutdevs/dracut/blob/master/man/dracut.cmdline.7.asc):
> rd.live.overlay=/dev/sdb1:persistent-overlay.img
This example has been in the dracut documentation since [2015](https://github.com/dracutdevs/dracut/commit/a1b4efe6a722ac3754d8a48109575d11d5ccf61b).
At the same time, improve the documentation with a more specific example.
Fixes [#579](https://github.com/dracutdevs/dracut/issues/579) (partially)
(Cherry-picked commit from dracutdevs/dracut#2253)
CC @FGrose @Conan-Kudo @fabiand

fix(dmsquash-live): handle relative pathspec

---

modules.d/95rootfs-block/mount-root.sh

This PR removes a command line option for a core dracut module.
"readonlyroot" and "noreadonlyroot" command line option are no longer supported (not sure if they actually ever fully worked). 
Use "ro" or "rw" instead.
I am open to keep these arguments and document them instead of removing them, but since there is a much more prevalent command line alternative, I do not think these are used."
Original commit from 2010: https://github.com/dracutdevs/dracut/commit/3871942d13b9175b8143f1ebbd48a211a007c7d2
Fixes [#1948](https://github.com/dracutdevs/dracut/issues/1948) (partially)
(Cherry-picked commit from dracutdevs/dracut#2264)

fix(rootfs-block): remove support for [no]readonlyroot and fastboot

---

dracut.sh

If `find_block_device` returns an error, the device must not be added to the list of host devices. E.g., a system with /etc mounted as overlay is pushing the empty string '' as host device.
```
//usr/bin/dracut@1658(): readlink -f /etc
/usr/bin/dracut@1658(): mp=/etc
/usr/bin/dracut@1659(): mountpoint /etc
//usr/bin/dracut@1660(): find_block_device /etc
//usr/lib/dracut/dracut-functions.sh@366(find_block_device): local _dev _majmin _find_mpt
//usr/lib/dracut/dracut-functions.sh@367(find_block_device): _find_mpt=/etc
//usr/lib/dracut/dracut-functions.sh@369(find_block_device): [[ '' != yes ]]
//usr/lib/dracut/dracut-functions.sh@370(find_block_device): [[ -d /etc/. ]]
//usr/lib/dracut/dracut-functions.sh@371(find_block_device): findmnt -e -v -n -o MAJ:MIN,SOURCE --target /etc …
```

fix(dracut.sh): do not add device if find_block_device returns an error

---

modules.d/99base/dracut-lib.sh
modules.d/99img-lib/img-lib.sh

Check the size and available space in /run to enlarge it,
if needed.
Introduce the check_meminfo() function to dracut-lib.sh
to replace a less versatile sed call.
Also, use local variables,
use parameter expansion to assign a default value,
use test exit logic directly, where possible,
tweak comments,
and move the check_live_ram() function to img-lib.sh.
(Cherry-picked commit from dracutdevs/dracut#2551)

fix(check_live_ram): increase /run tmpfs size, if needed

---

.gitignore

modules.d/99base/switch_root use to be a native binary that was built, but not anymore.
(Cherry-picked commit from dracutdevs/dracut#2505)

chore(gitignore): remove modules.d/99base/switch_root from

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

Using the overlay size in the device mapper table allows the filesystem in the base image to be extended at runtime if the overlay is larger than the base image (i.e. this makes resize2fs /dev/mapper/live-rw work when rd.live.overlay.thin is used).
This patch changes the upper-bound of the live-rw device when the user requests to create a thin-provisioned overlay by specifying the rd.live.overlay.thin kernel parameter. The size of the overlay (typically 32GiB, but it can be specified by the user with a kernel parameter) is used rather than the size of the base image.
Users of Fedora Linux have been reporting this bug here: https://discussion.fedoraproject.org/t/fedora-liveos-root-system-and-available-ram/82531/1
CC @gregory-lee-bartholomew
(Cherry-picked commit from …

fix(dmsquash-live): use the overlay size with thin provisioning     

---

.github/workflows/lint.yml

Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR.
It is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the Files Changed tab, please see below.
This will resolve your issues with cleaning your codebase every time the new ShellCheck comes out: #2501
Differential ShellCheck only reports defects directly related to the PR/commit. So you can focus on defects caused by your changes and deal with the existing defects later.
(Cherry-picked commit from dracutdevs/dracut#2530)
CC @jamacku

Enable Differential ShellCheck

---

.github/workflows/integration.yml

Tests-04 is flaky (sometimes passes sometimes fails on a seemingly same environment) on openSUSE CI container. The tests is satbel on all other distros.
Flaky tests tent to confuse contributors and slow down the project - https://github.com/dracut-ng/dracut-ng/pull/67#issuecomment-2030868270 .
openSUSE CI container (and only this one) struggled with some other tests recently as well, see https://github.com/dracut-ng/dracut-ng/pull/29 and https://github.com/dracut-ng/dracut-ng/pull/23 .
Now that we use the openSUSE CI container to test network-legacy (https://github.com/dracut-ng/dracut-ng/pull/47), we can remove openSUSE from the non-networking tests and still get some CI coverage on openSUSE.

ci: disable running flaky tests on openSUSE

---

.github/workflows/pr.yml

Switch from https://github.com/dracutdevs/commisery-action to https://github.com/tomtom-international/commisery-action
Lets hope we do not need to maintain our own fork of Commisery.

ci: switch Commisery to upstream

---

dracut.sh

The kernel file, at least in AOSC OS, is named vmlinux instead of vmlinuz if uncompressed.
(Cherry-picked commit from dracutdevs/dracut#2626)
CC @Icenowy

fix(dracut.sh): recognize kernel file in /boot named vmlinux too

---

.github/workflows/pr.yml

Let's try to make commisery-action not very intrusive and disable some feature we do not need. If commisery-action is too intrusive, I do not mind turning it off completely, but lets see first if this helps.

ci: don't validate the pull request title

---

src/install/dracut-install.c

Reverts dracut-ng/dracut-ng#56
Fixes #76

revert(dracut-install): file created without restricting permissions

---

.github/workflows/integration.yml
test/TEST-20-NFS/test.sh

In addition make, sure that exportfs is available before attempting to run the tests.
Incorporated  commit from dracutdevs/dracut#2570.
If we do not run NFSv3 tests, the test is much more stable and does not time out.

test(NFS): enable NFSv4 tests

---

dracut-init.sh

We are already printing out by default what modules are installed so user can check what got installed.
No need to issue warning for a normal execution of dracut. 
This is confusing users - especially new users we hope to attract - as seen e.g. https://forum.garudalinux.org/t/want-to-try-and-help-test-dracut-now-is-the-time/23994/75

fix(dracut-init.sh): do not print by default if a modules is not installed

---

modules.d/98dracut-systemd/dracut-emergency.sh
modules.d/99base/dracut-lib.sh

Using halt will keep the HW still powered on. This can be confusing for users. The screen is blank, but for example the fan is still running and they have no idea what is going on. So let's call poweroff.
(Cherry-picked commit from dracutdevs/dracut#2332)
CC @AdamWill @lnykryn

fix(dracut-lib): use poweroff instead of halt

---

test/TEST-04-FULL-SYSTEMD/test-init.sh

Without this change the test seems to be flaky on all distributions (seen on Fedora, Debian as well).
Follow-up to https://github.com/dracut-ng/dracut-ng/pull/42
The error in the test run log:
```
2024-04-04T13:42:24.0379316Z [    3.642828] (sd-umount)[709]: Failed to unmount /usr: Device or resource busy
2024-04-04T13:42:24.0407632Z [    3.646058] systemd-shutdown[1]: Failed to finalize file systems, ignoring.
```
From the CI it looks like this resolved the flakiness. 
Here is a CI run on another PR that shows the failures - https://github.com/dracut-ng/dracut-ng/pull/97
I consider this PR to be a priority for CI and the project, so i added it to the release milestone.

test(FULL-SYSTEMD): use poweroff to shut down test

---

.github/workflows/container.yml
test/container/Dockerfile-Gentoo
test/container/Dockerfile-alpine

Switch from musl and OpenRC to glibc and systemd for Gentoo.
Use Alpine instead for musl and OpenRC testing.
Gentoo musl container is not compatible with actions/checkout version >=2 due to musl. Alpine container (with musl) does not have this issue, so this PR would allow us to remove the actions/checkout@1 workarounds as seen on https://github.com/dracut-ng/dracut-ng/pull/129 .
This PR does not enable yet any testing on the new Alpine container, so for now the Manualtest Action needs to be used for that.

ci: improve Gentoo container

---

test/container/Dockerfile-Gentoo
test/run-qemu

Tell the installkernel package to use Debians installkernel rather then systemd's kernel-instal
Fixes: #135
Remaining test failures (04, 10, 12, 13, 18) should recover after the PR lands and test runs will pick up the new container version

ci: adopt Gentoo container to run the test suite

---

.github/workflows/integration.yml
.github/workflows/manualtest.yml

Split out the test suite into basic tests and extended tests.
Add alpine to basic tests and re-add openSUSE to basic tests.
Move Gentoo from extended test to basic tests until https://github.com/dracut-ng/dracut-ng/issues/135 is resolved.
Add alpine to Manual tests.
This makes the CI green again.

ci: enable alpine for basic tests

---

dracut.sh

If the user asks for the dracut output to be reproducible, we should ensure objcopy produces a reproducible uki to.
(cherry picked from dracutdevs/dracut#2400)
CC @glance-

fix(dracut.sh): make uki's reproducible

---

modules.d/00systemd/module-setup.sh
modules.d/01systemd-coredump/module-setup.sh
modules.d/01systemd-journald/module-setup.sh

Some required libraries that used to be statically included are in the process to be opened via `dlopen()`.
References:
- https://github.com/systemd/systemd/pull/31131
- https://github.com/systemd/systemd/pull/31550
- https://github.com/systemd/systemd/pull/32019
Closes https://github.com/dracutdevs/dracut/issues/2642
(cherry picked from dracutdevs/dracut#2643)

fix(systemd): explicitly install some libs that will not be statically included

---

test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-11-LVM/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-20-NFS/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/TEST-63-DRACUT-CPIO/test.sh

Remove 'rd.debug' argument  - when set - from tests. It is used very inconsistently, some tests set this some do not.
Debug logs can be enabled outside of the tests.
This will make the CI run faster, subjectively more readable and more importantly in the same configuration as end users run it.
Even Github has an interface to enable debug log and do not expect debug log to be on by default.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

tests: disable debug log by default

---

modules.d/01systemd-sysext/module-setup.sh

- Support to confexts added in https://github.com/systemd/systemd/pull/26013 (instead of working on /usr and /opt, confext will extend only /etc).
- /usr/lib/extensions/ not supported since https://github.com/systemd/systemd/commit/de862276
- In addition to these two fixes, add only raw binary disk images contained in regular files, because dracut does not have a helper function to add directories recursively.
(cherry picked from dracutdevs/dracut#2342)

fix(systemd-sysext): handle confexts and correct extensions search path

---

test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-20-NFS/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh

We want to know if including dracut modules makes the test fail instead of masking issues by omitting dracut modules.
This PR increase test coverage and makes the tests simpler to maintain.
This PR exposed two issues (either with dracut itself or with the test suite)
- test 04 an issue with multipath dracut module for full systemd test. 
- test 12 on Ubuntu (only), that required explicitly omitting dbus to keep the test passing. 
These exposed new issues confirms the reasoning behind why this PR increases test coverage.
(Cherry-picked commit from dracutdevs/dracut#2258)

fix(test): do not omit dracut modules for initramfs.testing

---

.github/workflows/container.yml
.github/workflows/integration.yml
.github/workflows/manualtest.yml
test/container/Dockerfile-Void

Void is an well maintained distribution that can enable Dracut to be tested for compatibility with runit . 
Only adding the test container is required, the test is already passing on Void Linux (due to how the CI is designed we will only see the pass after the PR lands).
@classabbyamp, @zdykstra and @ahesford has been a significant supporter of Dracut both via code contributions and PR reviews.

ci: enable Void Linux for basic tests with runit

---

.github/workflows/integration.yml
test/TEST-63-DRACUT-CPIO/test.sh
test/container/Dockerfile-OpenSuse-latest
tools/test-github.sh

Since the test is well written, it will be just skipped if cargo is not in the test container.
Add cargo to the openSUSE test container.
Fixes https://github.com/dracut-ng/dracut-ng/issues/106
CC @ddiss

test(DRACUT-CPIO): enable building dracut-cpio when cargo is installed

---

.github/workflows/integration.yml

Using Arch container as often it has the latest version of systemd-networkd.
Fixes https://github.com/dracut-ng/dracut-ng/issues/108

ci: enable systemd-networkd testing

---

test/TEST-01-BASIC/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh

The recommended watchdog device is i6300esb for qemu.
Discussed at [#2180 (comment)](https://github.com/dracutdevs/dracut/pull/2180#discussion_r1097386251)
Seem the recommended watchdog device is i6300esb https://libvirt.org/formatdomain.html#watchdog-devices
Without this PR, tests produces the following log message
> [ 10.754346] ib700wdt: WDT device closed unexpectedly. WDT will not stop!
(cherry picked from dracutdevs/dracut#2213)

tests: remove ib700wdt kernel module from tests

---

modules.d/80test/hard-off.sh
test/TEST-12-RAID-DEG/finished-false.sh
test/TEST-12-RAID-DEG/test.sh

This PR removes about 70 lines of code while maintaining existing functionality.

test(RAID-DEG): make test 12 use the test dracut modules

---

test/TEST-17-LVM-THIN/create-root.sh
test/TEST-17-LVM-THIN/test.sh

It might be that the lvm dracut module should be improved instead of working around it in the test.
Regardless, I wanted to share what it takes to pass this test on Void.
Fixes #173
CC @classabbyamp

test(LVM-THIN): make sure dm_thin_pool Linux kernel module is loaded

---

test/TEST-14-IMSM/create-root.sh
test/TEST-14-IMSM/hard-off.sh
test/TEST-14-IMSM/test.sh

This PR removes about 70 lines of code while maintaining existing functionality.
Had to increase the storage for some of the test steps.

test(ISMS): make test 14 use the test dracut modules

---

test/TEST-15-BTRFSRAID/finished-false.sh
test/TEST-15-BTRFSRAID/hard-off.sh
test/TEST-15-BTRFSRAID/test.sh

This PR removes about 100 lines of code while maintaining existing functionality.

test(BTRFSRAID): make test 15 use the test dracut modules

---

dracut-init.sh
dracut.sh
modules.d/99base/module-setup.sh
modules.d/99shutdown/module-setup.sh

Since https://github.com/systemd/systemd/commit/ffc1ec73, /usr is mounted as read-only in the initramfs by default.
Fixes https://github.com/dracutdevs/dracut/issues/2588
Minimal viable subset of https://github.com/dracut-ng/dracut-ng/pull/114 . No documentation change to maintain backward compatibility.

fix(dracut): link hooks directory from /lib/dracut/hooks to /var/lib/dracut/hooks

---

test/container/Dockerfile-Gentoo

Improve systemd installation by enabling cryptsetup flag.
Remove non-systemd craft from Gentoo, since now the project has Alpine and Void container to test with.
Add some extra packages to enable more test coverage.
Fixes #135

fix(test): fixup Gentoo CI

---

test/TEST-13-ENC-RAID-LVM/finished-false.sh
test/TEST-13-ENC-RAID-LVM/hard-off.sh
test/TEST-13-ENC-RAID-LVM/test.sh

This PR removes about 100 lines of code while maintaining existing functionality.

test(ENC-RAID-LVM): make test 13 use the test dracut modules

---

test/TEST-17-LVM-THIN/finished-false.sh
test/TEST-17-LVM-THIN/hard-off.sh
test/TEST-17-LVM-THIN/test.sh

This PR removes about 100 lines of code while maintaining existing functionality.

test(LVM-THIN): make test 17 use the test dracut modules

---

modules.d/01systemd-bsod/module-setup.sh
test/container/Dockerfile-Arch
test/container/Dockerfile-Fedora-latest

Include https://www.freedesktop.org/software/systemd/man/latest/systemd-bsod.service.html
bsod depends on qrencode. Add qrencode to Arch and Fedora container to trigger testing.
While at it add astyle, jq to the Fedora container as well as it was missing for testing some of the dracut modules.

feat(systemd-bsod): dracut module for systemd-bsod

---

modules.d/01systemd-udevd/module-setup.sh

[99-systemd.rules](https://github.com/systemd/systemd/blob/main/rules.d/99-systemd.rules.in#L69) depends on systemd-sysctl

fix(systemd-udevd): add systemd-sysctl dependency

---

modules.d/01systemd-initrd/module-setup.sh

'dracut -m dracut-systemd' does NOT includes `systemd-udevd` dracut module into the generated initrd.
This PR fixes this obvious dependency issue.
`systemd-udevd` dracut module already depends on `systemd` dracut module, so no need to directly depend on it here.

fix(systemd-initrd): add systemd-udevd dependency

---

modules.d/01systemd-udevd/module-setup.sh

During a typical systemd-enabled initrd generation both [udev-rules](https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/95udev-rules/module-setup.sh) and systemd-udevd gets installed. This leads to duplicate file copying, that can be easily avoided just by removing the duplicate rules.
The performance benefit of this PR is negligent. More importantly this PR makes it easier to read, reason and maintain the code.
Added explicit dependency to make sure there is no regression for the `dracut -m systemd-udevd` invocation.

perf(systemd-udevd): remove duplicate rules

---

.github/workflows/container.yml
test/container/Dockerfile-Fedora-latest

biosdevname is not available on arm64, remove it form the container as it is not essential for testing.
install qemu instead of qemu-system-x86-core.
Do not use qemu step for amd64 containers to improve performance.

ci: enable Fedora for arm64

---

.github/workflows/container.yml

Resolving regression on pushing CI container introduced by https://github.com/dracut-ng/dracut-ng/commit/dc1b7ce2eb1234a00e8658751ffa7bb2ef2cc9b7
Fixes #

ci: multiplatform container needs to be built as one step

---

test/container/Dockerfile-Debian
test/container/Dockerfile-Ubuntu

`bluez` is required to test `bluetooth` dracut module.
`iscsiuio` is required to test `iscsi` dracut module.

ci: add more packages to Debian and Ubuntu container to enable more testing

---

modules.d/01systemd-networkd/module-setup.sh

systemd-networkd does not require dbus, see https://github.com/dracutdevs/dracut/issues/2378#issuecomment-1668136681 .
Now that the project has a systemd-networkd [test case](https://github.com/dracut-ng/dracut-ng/pull/147), it is observable that dropping dbus from the generated initrd does not break the test case.
Fixes (partially): #60 https://github.com/dracutdevs/dracut/issues/2378

fix(systemd-networkd): dbus is not a mandatory dependency

---

.github/workflows/integration.yml
modules.d/80test-root/module-setup.sh
modules.d/80test/module-setup.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/hard-off.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-18-UEFI/test.sh
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/finished-false.sh
test/TEST-35-ISCSI-MULTI/hard-off.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/finished-false.sh
test/TEST-40-NBD/hard-off.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-63-DRACUT-CPIO/test.sh

- Migrate NBD, DRACUT-CPIO and ISCSI-MULTI test to use test dracut modules
- Remove obsolete, duplicate or unused code
- Add iscsiuio.socket requirement to run the ISCSI tests
-  Switch over ISCSI-MULTI to run on systemd-networkd on the CI to have more tests coverage for systemd-networkd. The ISCSI-MULTI test itself is not specific to systemd-networkd (just as before).
This PR removes about 300 source code lines, and us such helps with readability and code maintenance.

  test: make more use of the test dracut modules

---

.github/workflows/integration.yml

After https://github.com/dracut-ng/dracut-ng/pull/201 gentoo container is now passing all the extended tests.

ci: add (back) gentoo to run the extended testsuite

---

src/dracut-cpio/src/main.rs

Building dracut-cpio gives the following warning
```
2024-04-22T15:51:17.1254236Z    Compiling dracut-cpio v0.1.0 (/__w/dracut-ng/dracut-ng/src/dracut-cpio)
2024-04-22T15:51:17.2454252Z warning: call to `.clone()` on a reference in this situation does nothing
2024-04-22T15:51:17.2455792Z    --> src/main.rs:289:27
2024-04-22T15:51:17.2456392Z     |
2024-04-22T15:51:17.2456871Z 289 |     let mut outpath = path.clone();
2024-04-22T15:51:17.2457815Z     |                           ^^^^^^^^ help: remove this redundant call
2024-04-22T15:51:17.2458601Z     |
2024-04-22T15:51:17.2459868Z     = note: the type `Path` does not implement `Clone`, so calling `clone` on `&Path` copies the reference, which does not do anything and can be removed
2024-04-22T15:51:17.2461595Z     = note: …
```

fix(cpio): eliminate compile time warning      

---

Makefile

dracut.html is now checked in, 'make clean' should no longer remove it
Follow-up fix to https://github.com/dracut-ng/dracut-ng/pull/104

fix: clean Makefile rule

---

modules.d/35connman/module-setup.sh
modules.d/35network-legacy/module-setup.sh
modules.d/35network-manager/module-setup.sh

The systemd-networkd module already [includes](https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/01systemd-networkd/module-setup.sh#L25) kernel-network-modules. Do the same for other networking related dracut modules.

fix: network-manager should include kernel-network-modules

---

modules.d/98dracut-systemd/module-setup.sh

rd.cmdline=ask requires systemd-ask-password dracut module.
Fixes #164

fix(dracut-systemd): include systemd-ask-password module

---

modules.d/90numlock/numlock.sh

Fix what was pointed out at https://github.com/dracut-ng/dracut-ng/pull/235#pullrequestreview-2020112273

fix(numlock): use the same shebang as other dracut modules

---

modules.d/00systemd/module-setup.sh

Remove duplicated systemd-ask-password rules from the systemd dracut module. systemd-ask-password gets already pulled in by dracut-systemd as a dependency.

perf(systemd): remove duplicate rules

---

modules.d/01systemd-networkd/module-setup.sh

Follow-up to https://github.com/dracut-ng/dracut-ng/pull/218 as discussed https://github.com/dracut-ng/dracut-ng/pull/218#pullrequestreview-2019133702

fix(systemd-networkd): drop networkctl as it has a dependency on dbus

---

modules.d/01systemd-initrd/module-setup.sh

Add systemd-journald systemd-tmpfiles as explicit dependencies to systemd-initrd.
This PR makes `dracut -m systemd-initrd` to generate a proper systemd based initrd.

fix(systemd-initrd): systemd based initrd needs journald and tmpfiles

---

test/container/Dockerfile-Ubuntu

Without this package UEFI test would fail with the following error
```
dracut[F]: Can't find a uefi stub '/usr/lib/systemd/boot/efi/linuxx64.efi.stub' \ to create a UEFI executable
```
Removed explicit systemd as it is already installed by other packages to align it with the Debian container to ease maintenance.

ci: add systemd-boot-efi package to Ubuntu container for UEFI stub

---

test/TEST-18-UEFI/test.sh

Adjust test case to the latest Debian and Ubuntu ovmf package.
```
$ zcat /usr/share/doc/ovmf/NEWS.Debian.gz 
edk2 (2023.11-2) unstable; urgency=medium
The 2MB ovmf pflash images, OVMF_CODE.*.fd and OVMF_VARS.*.fd, have now
been removed. Users of the 2MB pflash images should migrate to their 4MB
image counterparts:
OVMF_CODE.fd         -> OVMF_CODE_4M.fd
OVMF_CODE.ms.fd      -> OVMF_CODE_4M.ms.fd
OVMF_CODE.secboot.fd -> OVMF_CODE_4M.secboot.fd
OVMF_VARS.fd         -> OVMF_VARS_4M.fd
OVMF_VARS.ms.fd      -> OVMF_VARS_4M.ms.fd
2MB VAR images are not compatible with 4MB CODE images. Users must
migrate both CODE and VARS images simultaneously.
A migration guide is provided at:
/usr/share/doc/ovmf/howto-2M-to-4M-migration.md.gz
-- dann frazier <dannf@debian.org>  Wed, 27 Dec 2023 10:15:33 …
```

test(UEFI): add support for OVMF_CODE_4M.fd for Ubuntu 24.04

---

modules.d/80test/module-setup.sh
test/TEST-18-UEFI/test.sh
test/test-functions

Add at least one test in `hostonly` mode. `hostonly` mode is how most users experience dracut as a Linux distribution package. 
Needed to add `qemu` dracut module as a dependency to the `test` dracut module to make sure that kernel modules needed for a `qemu` run are loaded.
Needed to change the order of arguments to make sure that the test case can overwrite the default arguments in `test_functions`.
The `hostonly` mode triggers the following warning, which is expected, and confirms that the test is working.
```
Running in hostonly mode in a container!
```

test(UEFI): run the test both hostonly and no-hostonly modes

---

test/TEST-20-NFS/test.sh

Newer distribution versions needs more space.
Resolves the following error when running test on Ubuntu
```
++ mkdir -p /root
++ mount -t ext4 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_root /root
++ cp -a -t /root /source/bin /source/dev /source/etc /source/lib /source/lib64 /source/nfs /source/proc /source/run /source/sbin /source/sys /source/tmp /source/usr /source/var
cp: error writing '/root/usr/lib/x86_64-linux-gnu/libnl-route-3.so.200.26.0': No space left on device
cp: error writing '/root/usr/lib/x86_64-linux-gnu/libpcap.so.1.10.4': No space left on device
cp: error writing '/root/usr/lib/x86_64-linux-gnu/libresolv.so.2': No space left on device
cp: error writing '/root/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33': No space left on device
cp: error writing …
```

test(NFS): increase virtual disk space to accomodate Ubuntu 24.04

---

modules.d/98dracut-systemd/module-setup.sh

dracut-systemd is the "top" level dracut module that pulls in all the systemd dependent modules.
For non-systemd based distributions this check makes the initrd generation faster as it skips all the other the processing of systemd-initrd and systemd-udevd dracut modules.

perf(dracut-systemd): check for systemd binary

---

modules.d/99memstrack/module-setup.sh

memstrack is debugging tool and it is typically not installed. 
The package name procps-ng is distribution specific and confusing to print out in the console in a non-verbose mode.

fix(memstrack): move the console warning to be a comment

---

modules.d/90crypt/module-setup.sh
modules.d/90systemd-cryptsetup/module-setup.sh

Separate out systemd dependent part of crypt into it's own module.
This new `systemd-cryptsetup` module is dependent on the `crypt` module, so it inherits all the `check()` and `install()` etc functionality, that we do not need to duplicate.

feat(systemd-cryptsetup): new module for systemd-cryptsetup

---

dracut.sh

From: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/patches/dracut/dracut-riscv64-efi.patch
CC @valentindavid

fix(dracut): add support for RISC-V EFI

---

.github/labeler.yml

Add the follolwing labels:
- systemd-bsod
- systemd-network-management
- numlock
- systemd-cryptsetup

fix(github): add the recently introduced modules to the labeler

---

modules.d/90crypt/module-setup.sh
modules.d/90systemd-cryptsetup/module-setup.sh

In its current form, fido2, pkcs11, tpm2-tss dracut modules depend on systemd.
Fixes #

perf(crypt): move more rules to systemd-cryptsetup

---

modules.d/01systemd-pcrphase/module-setup.sh

If systemd and tpm2-tss dracut modules can be installed (e.g. they are not omitted and dependencies are met) than automatically include them into initrd. 
Fixes #92 #255 (partially)
CC @ossimoi @DanWin @adrelanos

feat(systemd-pcrphase): include systemd-pcrphase if dependencies are met

---

.github/workflows/codeql.yml

All other CI jobs run on ubuntu-latest.
https://github.com/actions/runner-images/issues/9848

ci: switch to ubuntu-latest

---

test/container/Dockerfile-Debian
test/container/Dockerfile-OpenSuse-latest
test/container/Dockerfile-Ubuntu
test/container/Dockerfile-Void
test/container/Dockerfile-alpine

Allow test rngd dracut module.
Triggered by discussion at https://github.com/dracut-ng/dracut-ng/pull/290

ci: add rng-tools package to all test containers to test rngd dracut module

---

modules.d/90kernel-modules/module-setup.sh

As reported on the Solus issue tracker and on the Arch forum some Fujitsu laptops apparently require the psmouse module to be loaded in order for the keyboard to be functional. At least the Fujitsu Lifebook T938 model laptop is known to require this.
Fixes N/A

fix(90kernel-modules): add psmouse for some Fujitsu laptops

---

test/container/Dockerfile-Debian
test/container/Dockerfile-OpenSuse-latest
test/container/Dockerfile-Ubuntu

Noted in the following line during running tests in some of the test containers that indicates lack of test coverage. This PR resolves that.
```
dracut[E]: Module 'systemd-pcrphase' depends on 'tpm2-tss', which can't be installed
```

ci: add tpm2-tools package to all test containers to test tpm2-tss dracut module

---

man/dracut.modules.7.asc
modules.d/01fips/fips-boot.sh
modules.d/01fips/fips-load-crypto.sh
modules.d/01fips/fips-noboot.sh
modules.d/01fips/fips.sh
modules.d/01fips/module-setup.sh
modules.d/90kernel-modules/parse-kernel.sh
modules.d/95lunmask/parse-lunmask.sh
modules.d/98dracut-systemd/dracut-pre-udev.sh

Change /etc/modprobe.d path to /run/modprobe.d in hooks.  
Fixes #253 (partially)

fix: /etc/modprobe.d --> /run/modprobe.d

---

dracut.sh

From https://github.com/OpenMandrivaAssociation/dracut/blob/master/dracut-044-bsdcpio-compat.patch
Make cpio invocations more compatible with bsdcpio -- the mode indicator has to be the first argument.

fix(dracut): bsdcpio compatibility

---

modules.d/99base/rdsosreport.sh

`blkid -o udev` is deprecated since [2012](https://github.com/util-linux/util-linux/commit/24d741d88a31863e82feb3f3a4516d7df006378b)
`udevadm info --export-db` logs the full content of the udev database.
(cherry picked from dracutdevs/dracut#2222)

fix(base): log the full udev database in rdsosreport

---

modules.d/01systemd-udevd/module-setup.sh
modules.d/95udev-rules/module-setup.sh

Remove duplicated rule from systemd-udevd.

fix(base): install /etc/udev/udev.conf in hostonly mode only

---

src/install/dracut-install.c

This reverts commit 5ac581ef66dd8f1939e771419824137aebbc8f66. 
Reverts https://github.com/dracutdevs/dracut/pull/2359 .
Fixes #307
CC @FGrose

revert(dracut-install): check the existing file—not the source

---

modules.d/01systemd-ask-password/module-setup.sh

A password cannot be entered if there is no graphical output during boot, as is the case in aarch64, where `efifb` does not work with `qemu-system-aarch64`:
- `virtio-gpu-pci` does not expose a linear framebuffer
- `virtio-vga` is not supported
- `ramfb` is not enough
Therefore, depend on the `drm` module if `virtio_gpu` is loaded on the system.
Issue detected on aarch64 encrypted images, where there is no password prompt on the default console.

fix(systemd-ask-password): no graphical output in aarch64

---

modules.d/01fips/module-setup.sh

Random device nodes were required to workaround libgcrypt initialization problem (see https://bugzilla.redhat.com/show_bug.cgi?id=1401444) which is gone since libgcrypt-1.10 (2022): modern Linux kernels (3.17+) support getrandom() syscall and libgcrypt has switch to using getentropy() (glibc-2.25+).
The requirement to run dracut as root (which is needed to mknod /dev/{random,urandom}) is a particular problem for building UKIs in distro build systems where packages are not built by a privileged user.
Note, dracut itself always pre-creates /dev/{null,kmsg,console,random,urandom} devices when running privileged so the patch has no effect on 'traditional' setup.
'fips' module doesn't pre-create /dev/{random,urandom} anymore and thus can run unpriviliged.
- [ X ] I have tested it locally
- [ - …

fix(fips): Remove /dev/{random,urandom} pre-creation

---

man/dracut.cmdline.7.asc
modules.d/99base/init.sh

Follow-up to https://github.com/dracut-ng/dracut-ng/pull/124  .
`rd.udev.log-priority` is deprecated since systemd-v247 (https://github.com/systemd/systemd/commit/64a3494c)
Fixed documentation.

fix(base): add support for rd.udev.log_level

---

modules.d/90crypt/parse-crypt.sh

This pull request changes the default for unlocking LUKS encrypted devices at boot for generic images from previously only doing so when rd.auto=1 was specified. It is based on https://github.com/dracutdevs/dracut/pull/2520
Fixes #255

fix(crypt): unlock encrypted devices by default during boot

---

modules.d/90systemd-cryptsetup/module-setup.sh

This pull request adds missing modules potentially required for disk decryption to a generic initrd. It is based on https://github.com/dracutdevs/dracut/pull/2520

fix(systemd-crypt): add potentially needed modules to generic initrd

---

.github/labeler.yml
modules.d/90kernel-modules/module-setup.sh
modules.d/90pcmcia/module-setup.sh
modules.d/95udev-rules/module-setup.sh

Main motivation is to move out obsolete infrastructure from the core modules. This allows downstream packaging to completely remove the support, while still provide limited support upstream.
Related read: https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/char-misc.git/commit/?h=char-misc-next&id=9b12f050c76f090cc6d0aebe0ef76fed79ec3f15

feat(pcmcia): factor out pcmcia support into its own module

---

dracut.sh

intel-microcode uses the .initramfs suffix for the ucode files.
Reference 
- https://packages.debian.org/sid/amd64/intel-microcode/filelist
- https://salsa.debian.org/debian/dracut/-/blob/master/debian/patches/microcode
CC @bdrung

fix(dracut): microcode loading

---

modules.d/01systemd-pcrphase/module-setup.sh

Follow-up to https://github.com/dracut-ng/dracut-ng/pull/256. 
Fixes #

fix(systemd-pcrphase): in hostonly mode do not try to include systemd-pcrphase

---

src/install/dracut-install.c

libkmod reads the `modules.*.bin` files in the kernel dir every time we call one of the `kmod_module_new_from_lookup()` function. We end up calling it a lot especially in ARM64 systems where we handle fw_devlink supplier relations, which slows down things by a significant margin.
Instead, have it read these files at the start of the dracut-install run so the module information can be looked up quicker. We don't need to unload these resources in the cleanup function because libkmod handles that itself in `kmod_unref()`.
This helps mitigate #316 a bit, but does not entirely fix it.
<details><summary>Benchmarks on ARM64 (mt8183-kukui-jacuzzi-cozmo)</summary>
Before:
```
$ hyperfine './dracut-install -D "$(mktemp -d)" --kerneldir "/lib/modules/$(uname -r)" -o -m $(lsmod | cut -d" " -f1)' …
```

perf(dracut-install): preload kmod resources for quicker module lookup

---

test/TEST-12-RAID-DEG/test.sh

`test-functions` defines `DRACUT` to allow running the test out of tree against the system-installed dracut.
Fixes: 55e7b7ce6fcf ("test(RAID-DEG): make test 12 use the test dracut modules")

test(RAID-DEG): fix running test out of tree

---

shell-completion/bash/dracut
shell-completion/bash/lsinitrd

Debian's lintian complains about bash-completion-with-hashbang:
> This file starts with the #! sequence that marks interpreted scripts, but it is a bash completion script that is merely intended to be sourced. Please remove the line with hashbang, including any designated interpreter. Please refer to https://salsa.debian.org/lintian/lintian/-/merge_requests/292#note_139494 for details.
Remove hashbang from bash completions and add a shellcheck directive instead.

fix(shell-completion): remove hashbang from bash completions

---

test/test-functions

The Debian/Ubuntu autopkgtest runs the tests out of tree. In that environment `gcc` might not be installed, but it is needed to compile `logtee`.
So support running the tests with `V=2` but without `logtee`. Only use `logtee` if it is available.

feat(test): support V=2 without logtee

---

.shellcheckrc

The shellcheck SC2039 warning has been retired in favor of individual SC3xxx warnings for each individual issue. So remove the override from `.shellcheckrc`.

chore(shellcheck): remove retired SC2039

---

test/run-qemu

Running the tests on an AMD Ryzen 7 5700G without KVM, qemu-system-x86_64 will print following warnings:
```
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EDX.spec-ctrl [bit 26]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EDX.spec-ctrl [bit 26]
```
Use `-cpu max` by default to avoid those warnings.
Commit 3f56d481e8a3 ("test: …

fix(test): use `-cpu max` by default

---

.shellcheckrc
modules.d/01fips/fips.sh
modules.d/98dracut-systemd/dracut-cmdline-ask.sh
modules.d/99base/init.sh

Move the shellcheck overrides for `SC3045` to the individual occurrences instead of disabling this check globally to not hide valid complains like:
```
In modules.d/01fips/fips.sh line 97:
read -d '' -r FIPSMODULES < /etc/fipsmodules
^-- SC3045 (warning): In POSIX sh, read -d is undefined.
```
`read -d` is not supported by dash. `/etc/fipsmodules` is generated by `installkernel` in `modules.d/01fips/module-setup.sh` and contains kernel module names. So use a while read construct for reading this file.

fix(01fips): replace read -d that is not supported by dash

---

modules.d/80test-root/module-setup.sh

The variable `_terminfodir` refers to a path and therefore is safe to be quoted.

fix(test-root): quote _terminfodir variable

---

dracut.sh

The variable `strip_cmd` refers to a path and therefore is safe to be quoted.

fix(dracut): quote strip_cmd variable

---

modules.d/95nfs/nfsroot-cleanup.sh

The variable `rpcpipefspath` refers to a path and therefore is safe to be quoted.

fix(nfs): quote rpcpipefspath variable

---

dracut-init.sh

The variable `dracutbasedir` refers to a path and therefore is safe to be quoted.

fix(dracut-init.sh): quote dracutbasedir variable

---

modules.d/90kernel-modules/module-setup.sh

Corresponding kernel symbol blk_cleanup_disk is no longer used in the nvdimm driver and calls are made directly instead.
blk_alloc_disk is used to match the driver:
https://elixir.bootlin.com/linux/v6.1-rc8/source/drivers/nvdimm/pmem.c#L522
Adds `blk_alloc_disk` to list of symbols which pull kernel modules to initrd.
Resolves: RHEL-32237

fix(90kernel-modules): install blk modules using symbol blk_alloc_disk

---

modules.d/99base/dracut-lib.sh

The variable `_b` contains a digit without spaces (as validated by `isdigit`) and therefore is safe to quote.
The variable `var` refers to one environment variable and therefore is safe to quote.

fix(dracut-lib): quote _b and var variable

---

modules.d/95lunmask/fc_transport_scan_lun.sh
modules.d/95lunmask/sas_transport_scan_lun.sh

shellcheck complains about SC2086 (info): Double quote to prevent globbing and word splitting.
The variable `LUN` refers to a single logical unit number (LUN) and therefore is safe to be quoted.

fix(lunmask): quote LUN variable

---

modules.d/98syslog/rsyslogd-start.sh

The variable `conf` refers to a path and therefore is safe to be quoted.

fix(syslog): quote conf variable

---

dracut.sh

shellcheck complains:
```
In dracut.sh line 1382:
&& dracut_args[$i]="\"${dracut_args[$i]}\""
^-- SC2004 (style): $/${} is unnecessary on arithmetic variables.
```

fix(dracut): fix shellcheck SC2004

---

modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
modules.d/95iscsi/iscsiroot.sh

shellcheck complains:
```
In modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh line 12:
[ -n "$_lvm2_thin_device" ] && return $?
^-- SC2319 (warning): This $? refers to a condition, not a command. Assign to a variable to avoid it being overwritten.
```
Let `is_lvm2_thinp_device` directly return the test exit code.
shellcheck complains:
```
In modules.d/95iscsi/iscsiroot.sh line 232:
[ -z "$targets" ] && warn "Target discovery to $iscsi_target_ip:${iscsi_target_port:+$iscsi_target_port} failed with status $?" && return 1
^-- SC2319 (warning): This $? refers to a condition, not a command. Assign to a variable to avoid it being overwritten.
```
The `while` loop that gets the output from `iscsiadm` via a pipe will exit with 0. Printing the exit code 0 does not help. So just drop it.

fix: address shellcheck SC2319

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

The variables `pathspec`, `live_dir`, `squash_image`, `SQUASHED`, and `FSIMG` refer to paths or filenames. Therefore they are safe to quote.
Fixes #

fix(dmsquash-live): quote variables

---

dracut-init.sh

Look for rules files in /etc/udev/rules.d first so that local modifications of system files are included.

dracut-init: change lookup order for rules files

---

modules.d/80test-root/test-init.sh
modules.d/99base/dracut-lib.sh
test/TEST-20-NFS/client-init.sh
test/TEST-30-ISCSI/client-init.sh
test/TEST-35-ISCSI-MULTI/client-init.sh
test/TEST-40-NBD/client-init.sh

The variable `CTTY` contains either nothing or exactly one parameter. Use shell substitution to quote this single parameter in case it is not empty.
The variable `_ctty` contains a path and therefore is safe to quote.

fix: quote single CTTY parameter and _ctty variable

---

modules.d/90dmsquash-live-autooverlay/create-overlay.sh

Instead of ignoring those complains fix them instead. The variable `overlay` should be quoted since it might contain spaces. The variables `rootDevice`, `rootDeviceAbsolutePath`, `rootDeviceSysfsPath`, `fullDriveSysfsPath`, `blockDevice` refer to paths. Therefore they are safe to quote.

fix(dmsquash-live-autooverlay): quote variables

---

modules.d/95znet/module-setup.sh

The variable `initdir` refers to a path and therefore is safe to be quoted.

fix(znet): quote initdir variable

---

modules.d/35network-legacy/parse-bridge.sh

shellcheck complains about SC2086 (info): Double quote to prevent globbing and word splitting.
The variable `bridgename` refers to a bridge name which is not expected to contain a space and therefore is safe to be quoted.

fix(network-legacy): quote bridgename variable

---

modules.d/30convertfs/convertfs.sh

The variable `CP_HARDLINK` contains either nothing or exactly one parameter. Use shell substitution to quote this single parameter in case it is not empty.

fix(convertfs): quote single CP_HARDLINK variable

---

modules.d/91zipl/module-setup.sh

The variable `ID_FS_TYPE` refers to a single file system type which is not expected to contain a space and therefore is safe to be quoted.

fix(zipl): quote ID_FS_TYPE variable

---

modules.d/91zipl/parse-zipl.sh

Only strings without spaces are assigned to the `zipl_env` variable. Therefore it is safe to be quoted.

fix(zipl): quote zipl_env variable

---

dracut-logger.sh

The variable `_dlogfd` refers to an integer and therefore is safe to be quoted.

fix(dracut-logger.sh): quote _dlogfd variable

---

modules.d/90kernel-modules/module-setup.sh
modules.d/90multipath/module-setup.sh
modules.d/95fcoe-uefi/module-setup.sh
modules.d/95fcoe/module-setup.sh
modules.d/95iscsi/module-setup.sh
modules.d/95lunmask/module-setup.sh
modules.d/95nvmf/module-setup.sh

shellcheck 0.10 complains about SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly). It fails to detect cases where a function is defined and later called by `for_each_host_dev_and_slaves`. Disable shellcheck in this case.

fix: disable SC2317 for calls by for_each_host_dev_and_slaves

---

.github/workflows/integration.yml
test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-18-UEFI/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh

This PR only changes the test suite, no dracut module is changed by this PR.
Even with these changes the following tests are failing on Arch with systemd 256: 12, 14, 16.
Temporary remove Arch from running the extended test suite until the root cause of these failures are identified. 
Some other tests (such as test 01 and some networking tests are passing on Arch with this change, those will continue to run on the CI.
Fixes #382 (partially)

tests: use --add instead of --modules to create test-makeroot

---

dracut-init.sh
modules.d/01systemd-coredump/module-setup.sh
modules.d/01systemd-journald/module-setup.sh
modules.d/01systemd-networkd/module-setup.sh
modules.d/01systemd-resolved/module-setup.sh
modules.d/01systemd-sysusers/module-setup.sh
modules.d/01systemd-timesyncd/module-setup.sh
modules.d/06dbus-broker/module-setup.sh
modules.d/91tpm2-tss/module-setup.sh

Refactor the way systemd-sysusers config files gets installed to make it easier for distributions to customize.
CC @AndrewAmmerlaan

refactor: use inst_sysusers to install sysusers files

---

dracut.sh

shellcheck complains about SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
The function `read_arg` is not used anywhere any more (only `configure` uses its own copy). So drop this unused function.
Fixes: ffa71b4afa3e ("dracut.sh: use getopt to parse arguments")

fix(dracut.sh): drop unused read_arg function

---

test/TEST-40-NBD/test.sh

The NBD tests so far were near totally borked.
They were actually failing a lot, but due to the test_run() function ending with killing the server, which always succeeded, that was the results the tests actually returned.
This PR will probably break CI, but it just un-hides breakage that was there before, but counted as pass.

Fix nbd tests

---

modules.d/30convertfs/convertfs.sh

shellcheck complains about SC2317 (info):
It fails to detect cases where a function is defined and later called by a trap. Disable shellcheck in this case.
Fixes #

fix(convertfs): disable SC2317 for EXIT trap function

---

test/TEST-98-GETARG/test.sh

shellcheck 0.10 complains about SC2317 (info):
It fails to detect cases where a function is defined and later called by `getarg` or existing functions are overridden. Disable shellcheck in these cases.

test: disable SC2317 in test 98

---

modules.d/30convertfs/convertfs.sh

shellcheck complains about SC2317 (info):
The function `find_mount` is not called in `convertfs.sh` any more. So drop this unused function.
Fixes: 101b683e1a2 ("refactor(convertfs): drop duplicate def. of ismounted()")

fix(convertfs): drop unused find_mount function

---

dracut-logger.sh

shellcheck 0.10 complains about SC2317 (info):
It fails to detect that these logger functions are called later by scripts that source `dracut-logger.sh`. Disable shellcheck in this case.

fix(dracut-logger.sh): disable SC2317 for logger functions

---

.github/workflows/integration.yml
modules.d/01systemd-networkd/99-default.network
modules.d/01systemd-networkd/99-wait-online-dracut.conf
modules.d/01systemd-networkd/module-setup.sh
modules.d/01systemd-networkd/networkd-config.sh
modules.d/01systemd-networkd/networkd-run.sh
test/TEST-40-NBD/test.sh

This adds support for the networkd networking module to actually bring up netroots.
It's based on how the connman module does it, adapted for networkd.
networkd (like dhclient, which gets told about them here: https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/35network-legacy/dhclient.conf#L8) needs to be told to request specific options. Like the route-path or its DHCPv6 equivalent (which are as of yet unused by dracut and unsupported by systemd-networkd).
Likewise, the dhclient config used to enable hardware/mac mode for the client-identifier(https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/35network-legacy/dhclient.conf#L4). This sets the equivalent networkd setting so people don't have to adjust their dhcp servers config when switching between the two modules, just …

systemd-networkd: add support for proper netroot invocation

---

dracut-functions.sh

The `get_maj_min()` cache lookup is commonly used across many flows. While `awk` should be available, some highly constrained environments may not have it. A second call to `grep` can provide the same behaviour without adding a dependency.
Lines in the cache will be of the form "/dev/sda2 8:2". `awk '{print $NF}'` returns the last word of a matching line. Since the initial matching regex is so specific a second call to grep can easily extract the last word.
Source: https://github.com/microsoft/azurelinux/pull/9210

fix(dracut-functions): avoid awk in get_maj_min() 

---

modules.d/90qemu/module-setup.sh

The virtio crypto is a virtual crypto device.
- https://wiki.qemu.org/Features/VirtioCrypto

feat(qemu): include the virtio_crypto kernel module

---

.github/workflows/integration.yml
test/TEST-20-NFS/test.sh

Reenable systemd-networkd for TEST-NFS on Arch.
Fixes #382 (partially)
CC @BtbN for visibility

fix(TEST-NFS): use --add instead of --modules to create test-makeroot

---

test/TEST-10-RAID/test.sh
test/TEST-12-RAID-DEG/test.sh

As the git repository is growing (e.g. by adding files at https://github.com/dracut-ng/dracut-ng/pull/389), some tests starts failing as the drive runs out of space. Fix it.

fix(test): tests needs more storage space

---

test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/test-functions

Resolve regression from https://github.com/dracut-ng/dracut-ng/pull/252 .
Follow-up to https://github.com/dracut-ng/dracut-ng/commit/1993786f8aa183ce44705fce2a748cefdd2ed5c9
Linux kernel arguments should not be set with --kernel-cmdline, see #400

test: use --kernel-cmdline to set only dracut arguments

---

dracut.sh

intel-microcode on Debian/Ubuntu uses the `.initramfs` suffix for the ucode files (e.g. `/lib/firmware/intel-ucode/06-9e-0b.initramfs`). `get_ucode_file` returns `family-model-stepping` on Intel (e.g. `06-9e-0b`). If the microcode file is found, the loop is broken. Otherwise `.early` is appended to the name (e.g. `06-9e-0b.early`) and tried again. If that file is not found, `.initramfs` is appended to the name (e.g. `06-9e-0b.early.initramfs`), but this suffix should be appended to the initial name (e.g. `06-9e-0b.initramfs`).
Fixes: 16573680d1b6 ("fix(dracut): microcode loading")
Fixes #

fix(dracut): microcode loading named .initramfs

---

modules.d/09dbus/module-setup.sh

shellcheck complains about SC2317 (info):
The last `return 1` statement is not reachable. Remove it and move the else clause one level up because the if clause returns from the function.

fix(dbus): drop unreachable return statement

---

dracut-catimages.sh

shellcheck complains about SC2317 (info):
The function `dwarning` is not called in `dracut-catimages.sh`. So drop this unused function. It can be re-introduced once it is needed.

fix(dracut-catimages.sh): drop unused dwarning function

---

lsinitrd.sh

shellcheck 0.10 complains about SC2317 (info):
It fails to detect that these functions are assigned to `CAT` and `$CAT` is called later. Disable shellcheck in this case.

fix(lsinitrd.sh): disable SC2317 for cat functions

---

dracut-initramfs-restore.sh

Quoting the globbing `*` will prevent Bash from use globbing. So only quote the kernel version variable that could potentially contain spaces.
Fixes: 28820e205328 ("feat(dracut.sh): make initramfs-${kernel}.img filename configurable")

fix(dracut-initramfs-restore.sh): correct initrd globbing

---

modules.d/01systemd-hostnamed/module-setup.sh

Added in systemd v256
Add `systemd-hostnamed.socket` to the initrd to not have `Failed to bind to Varlink socket` messages.
Fixes #420

fix(systemd-hostnamed): add missing systemd-hostnamed.socket

---

.github/workflows/integration.yml
test/TEST-12-RAID-DEG/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-16-DMSQUASH/test.sh

Passing tests require omitting some dracut modules, which is likely masking some dracut bugs, but the changes in this PR still increases test coverage overall even with the potential masking of some systemd related dracut bugs. 
Fixes #382

fix(test): reenable extended tests for Arch

---

modules.d/90crypt/module-setup.sh

dracut has a "hidden" and undocumented `force` crypttab option (added with commit b7058d0ce5e99cbc80b5f760a0b654d3ff03c094). This option forces the inclusion of a crypttab entry in the initrd, which is useful in some cases where the filesystem check (for whatever reason) does not report a required encrypted device as "crypto_LUKS".
On the other hand, systemd provides the `x-initrd.attach` crypttab option since v245. Excerpt from `crypttab(5)`:
```
x-initrd.attach
Setup this encrypted block device in the initrd, similarly to systemd.mount(5)
units marked with x-initrd.mount.
```
This crypttab option is commonly used to mark encrypted block devices that contain filesystems mounted in the initrd. So, this patch aims to make use of this well-known systemd crypttab option to match the …

feat(crypt): force the inclusion of crypttab entries with x-initrd.attach

---

modules.d/01systemd-hostnamed/module-setup.sh

Followup to https://github.com/dracut-ng/dracut-ng/pull/421
I didn't know systemd is shipping these files rather than enabling the units via presets and due to the reproducer in #420 pulling the unit in explicitely this was noticed in local testing.
Fixes #420

fix(systemd-hostnamed): Also enable socket units

---

src/install/dracut-install.c
src/install/hashmap.c
src/install/hashmap.h

find_kmod_module_from_sysfs_node() is called for every platform device in the system via find_suppliers(). In turn, this calls kmod_module_new_from_lookup() for every device modalias. This is an expensive call that reads the modalias files every single time from scratch.
On many platforms, there are many identical platform devices (e.g. multiple serial ports, or dozens or hundreds of power domain devices). Therefore, it's worth memoizing this so we only perform the expensive lookup once per unique modalias.
This cuts down dracut generation time on an Apple M1 Pro MacBook Pro from 63 seconds to 24 seconds, give or take, after 80f2caf4f5ee (in fact, this new code/behavior in dracut-ng was the root cause of the major perf regression that was improved in that commit).
Memoize …

Memoize find_kmod_module_from_sysfs_node

---

modules.d/90crypt/cryptroot-ask.sh

fix(rt): use singular argument for timeout value
use singular argument for timeout value -- plural values create an invalid cryptsetup command line.
Changes
Checklist
I have tested it locally
I have reviewed and updated any documentation if relevant
I am providing new code and test(s) for it
Fixes https://github.com/dracut-ng/dracut-ng/issues/424

fix(rt): use singular argument for timeout value

---

modules.d/01systemd-udevd/module-setup.sh
modules.d/95udev-rules/module-setup.sh
test/TEST-35-ISCSI-MULTI/test.sh

Install all udev dependencies as part of the udev-rules dracut modules.
For non-systemd initrd's this will make devices properly initialized (at the expense of slightly more storage space).

fix(udev-rules): install more udev rules even if systemd is not installed

---

modules.d/01fips/module-setup.sh

Remove reference to kernel module zlib (deprecated in kernel v4.6+) since the pedantic dracut behavior causes initramfs generation to fail otherwise.
See: https://cateee.net/lkddb/web-lkddb/CRYPTO_ZLIB.html
Source: https://raw.githubusercontent.com/microsoft/azurelinux/3.0-dev/SPECS/dracut/0011-Remove-reference-to-kernel-module-zlib-in-fips-module.patch

Remove reference to kernel module zlib in fips module

---

.github/labeler.yml
modules.d/01systemd-udevd/module-setup.sh
modules.d/95hwdb/module-setup.sh
modules.d/95udev-rules/module-setup.sh

This PR is just a refactor. hwdb module is installed by default.
This PR makes it possible to omit the hwdb when it is safe to do with 'dracut -o hwdb' command line option.
This refactor allows to make further progress on #203.
CC @pvalena

feat(hwdb): separate out hwdb module

---

modules.d/06dbus-daemon/module-setup.sh

The dbus daemon not actually running has surprisingly little ill effects, since systemctl falls back to some built-in backup of pid1 to do its thing.
But one issue I ran into was that networkd was not setting the hostname it was sent via DHCP. Turns out this is due to there being no running dbus, so it fails to communicate the hostname-change to hostnamed.
It also makes debugging issues in an emergency shell a lot harder, since most systemd-commands outside of systemctl are inoperative.
The two units don't have an Install-Section. They instead ship with respective links to them in the systems unit directory.
So those just need to be copied as well.
Fixes #309

fix(dbus-daemon): actually enable the dbus service and socket

---

.github/workflows/integration.yml
test/run-qemu

Test 40 runs out of memory. Give the VMs more RAM (2GB). With this change, CI can now run Test 40 on Arch and openSUSE as well. Now it only fails on Gentoo and Ubuntu (for other additional reasons).
Fixes #193 (partially)

test: increase VM memory size to pass test 40 on more VMs

---

test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/test-functions
tools/test-github.sh

In general, CI should be testing what most users - which is usually the default configuration. 
In this case, it also make test coverage higher with selinux potentially enabled.

test: do not disable selinux for tests

---

dracut.conf.d/50-ima.conf.example

Source: https://github.com/openSUSE/dracut-ng/commit/dd118bab29a38fa221cedc7d66a91f3ff40f9f6b
Related read: https://en.opensuse.org/SDB:Ima_evm#Enabling_IMA/EVM_during_early_boot

feat: add common config for Integrity Measurement Architecture (IMA) 

---

man/dracut.asc
modules.d/98dracut-systemd/dracut-shutdown.service.8.asc

Since 4f03054e540427682221e4c62b4d44f79424e38a, these shutdown steps have been in response to the ExecStop= called from the sysinit.target.
Correct the doc in the two places it mentions this.

docs: correct shutdown path disucssion

---

.github/workflows/integration.yml

CI is now no longer stable, in particular iscsi tessts (30, 35) and nbd test (40) fail at seemingly random runs with seemingly random configuration. This PR is an attempt to re-stabilize the CI.
This PR changes the strategy to run these tests sequentially (by setting `max-parallel: 1`), no change in tests itself.
Change the order of tests and put the networking/slow tests at the end of the CI run.

test: run some networking tests sequentially to make it less flaky

---

test/container/Dockerfile-Debian
test/container/Dockerfile-Ubuntu

PR to enable testing systemd-coredump module.

ci: add systemd-coredump to Debian/Ubuntu containers

---

test/TEST-04-FULL-SYSTEMD/create-root.sh
test/TEST-04-FULL-SYSTEMD/fstab
test/TEST-04-FULL-SYSTEMD/test.sh

- Include more systemd modules. Most of modules added had no test coverage in any of the tests on CI.
- Add a test for encrypted root
- remove /etc/fstab from the rootfs. This PR moves /usr mounting into initrd instead of after switch_root.

test(FULL-SYSTEMD): add a test for encrypted root

---

modules.d/80test-root/test-init.sh

There is no need to remount rootfs read only right before shutdown.

test: avoid writing to rootfs as it might be read-only

---

test/TEST-40-NBD/test.sh

Remove NFS related kernel modules from the NBD test. remove networking modules that are installed by kernel-network-modules.

test(TEST-40-NBD): no need to add kernel modules manually

---

man/dracut.usage.asc

Since some distributions set hostonly the default, suggesting that it is only for experts is a bit of overstatement.

docs: remove suggesting that hostonly option is only for experts

---

dracut-initramfs-restore.sh
lsinitrd.sh

The initrd filename can be configured via `initrdname`. Support this feature also in `lsinitrd` (similar to the code in `dracut-initramfs-restore.sh`).
Fix: 28820e205328 ("feat(dracut.sh): make initramfs-${kernel}.img filename configurable")
Fixes #

feat(lsinitrd.sh): support configurable initrd filenames

---

modules.d/45net-lib/module-setup.sh

- `pgrep`, `tr` not needed.
- `sed` installed by `base`.

fix(net-lib): require and install only the necessary binaries

---

test/test-functions

If the test cases are run in verbose with (i.e. with `V=1` or `V=2` set), do not add `quiet` to the kernel cmdline.

test: drop 'quiet' from kernel cmdline on verbose runs

---

modules.d/95nfs/module-setup.sh
modules.d/95nfs/nfs-lib.sh
modules.d/95nfs/nfs-start-rpc.sh
modules.d/95nfs/parse-nfsroot.sh

The Debian/Ubuntu package `rpcbind` creates a user named `_rpc`. Support running `rpcbind` with that user. Add a helper function `get_rpc_user` that derives the desired user from parsing `/etc/passwd`.

fix(nfs): support rpcbind user named _rpc

---

modules.d/00systemd/module-setup.sh

Make systemd consistent with [systemd-ask-password](https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/01systemd-ask-password/module-setup.sh#L51)
Resolves the following error on Debian based systems
```
Failed to add dependency on unit, unit systemd-vconsole-setup.service does not exist.
Failed to add dependency on unit, unit systemd-vconsole-setup.service does not exist.
```

fix(systemd): check for systemd-vconsole-setup.service

---

modules.d/90multipath/module-setup.sh

The multipath module is always included in no-hostonly mode, but including it in the initramfs might activate multipath on the root device, which could be undesirable. This behavior can be manually fixed by explicitly excluding the root device from multipath in /etc/multipath.conf.
Therefore, issue a warning in no-hostonly mode, if there is no multipath device and the user has not configured multipath.
EDIT: instead of warning, omit including multipath module.
bsc#1069169
Fixes #465
See:
- https://github.com/openSUSE/dracut/pull/239 
- https://github.com/openSUSE/dracut-ng/commit/03e801f4a27da27983f77d0e7d25779d21a822e1

feat(multipath): omit module if included with no multipath devices and no user conf

---

modules.d/01systemd-pcrphase/module-setup.sh

Only make tpm2-tss a dependency if requirements to install tpm2-tss is met.
Follow-up to https://github.com/dracut-ng/dracut-ng/pull/256 ,
Fixes #329
CC @dalto8

fix(systemd-pcrphase): make tpm2-tss an optional dependency

---

dracut-init.sh

Clarify that dracut module is missing and not Linux command or package.
This will help clarify to the users what action to take as a response of this message - 
Fixes #329
CC @dalto8

fix(dracut-init.sh): clarify the error message

---

modules.d/80test-root/test-init.sh
test/TEST-04-FULL-SYSTEMD/test-init.sh
test/TEST-04-FULL-SYSTEMD/test.sh

- test(FULL-SYSTEMD): add test with rd.luks.name
- test(FULL-SYSTEMD): do not disable kernel loglevel
- test(FULL-SYSTEMD): add tests for volatile mode
-  test(FULL-SYSTEMD): remove managing drivers manually
-  test(FULL-SYSTEMD): align with other tests
-  test(FULL-SYSTEMD): control decryption from command line
-  test(FULL-SYSTEMD): no need for explicit bash dependency
-  test(FULL-SYSTEMD): avoid hostonly files for a generic testcase
-  test(FULL-SYSTEMD): add systemd-coredump and systemd-pcrphase testing
-  test: move /failed to /run/failed as rootfs might be read-only

ci: improve FULL-SYSTEMD test

---

test/container/Dockerfile-Gentoo

I think this should be enough for the `FULL_SYSTEMD` tests, but lets see what the CI says.
Closes: https://github.com/dracut-ng/dracut-ng/issues/481

fix(Dockerfile-Gentoo): add requirements for systemd-pcrphase

---

src/install/dracut-install.c

When use clone ioctl to copy a file, the extended attributes of files are missing, which is inconsistent with the result by using the cp command. This commit add the process to copy extended attributes after clone_file().
Add the process to copy extended attributes after clone_file().
Fixes #

fix(dracut-install): copy xattr when use clone ioctl

---

modules.d/90kernel-modules/module-setup.sh

Most ARM Chromebooks need the ChromiumOS Embedded Controller drivers located under kernel/drivers/platform/chrome for essential functionality like keyboard, USB, and display backlight. Add them to the non-hostonly initramfs by adding them to the ARM/RISC-V-specific instmods call.
On Fedora 40 (ARM64), the following modules are added:
```
$ tree --du -h lib/modules/6.9.7-200.fc40.aarch64/kernel/drivers/platform/chrome
[ 99K]  lib/modules/6.9.7-200.fc40.aarch64/kernel/drivers/platform/chrome
├── [5.1K]  chromeos_acpi.ko.xz
├── [3.0K]  chromeos_privacy_screen.ko.xz
├── [5.7K]  cros_ec_chardev.ko.xz
├── [4.5K]  cros_ec_i2c.ko.xz
├── [5.2K]  cros_ec.ko.xz
├── [4.6K]  cros_ec_rpmsg.ko.xz
├── [ 14K]  cros-ec-sensorhub.ko.xz
├── [6.7K]  cros_ec_spi.ko.xz
├── [4.9K]  cros_ec_sysfs.ko.xz
├── [ 16K] …
```

feat(kernel-modules): Install platform/chrome modules on ARM/RISC-V

---

modules.d/90multipath/module-setup.sh
test/TEST-04-FULL-SYSTEMD/test.sh

Follow-up to 4957ffa935. Return 255 instead of 1 and change the order of checks.
This change also allows removing the multipath workaround the the FULL-SYSTEMD test.
CC @mwilck @bmarzins @aafeijoo-suse

fix(multipath): omit module if included with no multipath devices

---

test/TEST-14-IMSM/test.sh

Commit 061a1068ba4c872e48605b9b0ecd282f4630ea8f ("test: avoid writing to rootfs as it might be read-only") fixes the test failure with systemd
256. So revert the changes to `test/TEST-14-IMSM` from commit 130f4dfce48b187944be9a0cacca794dd32428ad.

fix(test): run test 14 with systemd again

---

modules.d/90dmsquash-live/module-setup.sh
test/TEST-16-DMSQUASH/create-root.sh
test/TEST-16-DMSQUASH/test.sh

Adds testing for erofs support in dmsquash-live, makes sure the erofs kernel module is installed when using dmsquash-live.

Erofs tests

---

modules.d/00systemd/module-setup.sh
modules.d/95udev-rules/module-setup.sh

- move installation of libkmod.so from systemd module to udev-rules module
Downstream bug report: https://bugs.gentoo.org/935548

fix(systemd): move installation of libkmod to udev-rules module

---

dracut.conf.d/50-no-xattr.conf.example
dracut.sh

Add common config to make it easier to disable xattr.
Running inside a container is not a good proxy for making decisions about filesystem properties.
Partial revert of https://github.com/dracutdevs/dracut/pull/1499
CC @cgwalters  @DaanDeMeyer for visibility

fix(dracut): re-enable extended attributes in containers

---

test/TEST-16-DMSQUASH/create-root.sh
test/TEST-16-DMSQUASH/test.sh

Only one partition is needed, so need need to repartition. This makes the code easier to reason about and test runs a bit faster.

test(DMSQUASH): no need to partition root_erofs disk

---

.github/CODEOWNERS

By using a GitHub team for the CODEOWNERS file, we can easily add and remove people through the interface for global committers and avoid unnecessary churn.

chore(github): use committer team for code owners

---

test/TEST-12-RAID-DEG/test.sh

130f4dfce48b187944be9a0cacca794dd32428ad inadvertently made this test flaky by including additional dracut modules not required to pass the test.
This PR should restore stable CI, but it masks some instabilities that will be tracked as part of https://github.com/dracut-ng/dracut-ng/issues/491.

test(RAID-DEG): make it not flaky

---

modules.d/04watchdog/watchdog.sh

i6300esb should be prioritized over ib700wdt.
The recommended watchdog device is i6300esb, see https://libvirt.org/formatdomain.html#watchdog-devices.
Follow-up to f0a7fc5b4 .
As the CI is using the `watchdog` module, should should make the CI more stable as well and eliminates the following warning
```
[    0.757152] watchdog: i6300ESB timer: cannot register miscdev on minor=130 (err=-16).
[    0.757902] watchdog: i6300ESB timer: a legacy watchdog module is probably present.
[    1.042544] ib700wdt: WDT device closed unexpectedly.  WDT will not stop!
```

fix(watchdog): change the priority of watchdog kernel modules

---

dracut.conf.d/50-no-network.conf.example

This is especially useful for distributions like Arch or Gentoo that do not package networking dracut modules into its own package.
Earlier relevant discussion for context: https://github.com/dracut-ng/dracut-ng/pull/297#issuecomment-2123395363

feat: add common config when networking is not desired

---

Makefile

This PR allows users and distributions to discover configuration examples and take advantage of them either during packaging or during using dracut.

fix(Makefile): install dracut config examples under /usr/lib/dracut/dracut.conf.d

---

.github/labeler.yml
modules.d/00shell-interpreter/module-setup.sh
modules.d/05busybox/module-setup.sh
modules.d/80test-makeroot/module-setup.sh
modules.d/99base/module-setup.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh

cherry-pick the dracut module from https://github.com/dracutdevs/dracut/pull/2564 and use it to improve the CI and demonstrate the usefulness of this new dracut module and fix all the exposed bugs.
If dash and busybox is NOT installed or **bash module gets included explicitly (as it happens always when systemd gets included), this module should have no impact in the generated initramfs.** 
The module is independent and additive - a distribution might decide not to package the module with core dracut modules.
One notable side effect of this PR is that now the CI has test coverage for the `busybox` dracut module (without explicitly mentioning `busybox` in any of the test case), since the on Alpine `/bin/sh` points to `busybox`. Getting test coverage without adding a lot of code is very …

feat(shell-interpreter): meta package for improved shell selection

---

modules.d/90crypt/parse-crypt.sh

This reverts commit 2339acfaeee60d6bb26a1103db2e53bc8f9cb2d1.
This change needs more test cases and more granular conditionals.
Fixes #492 , Reopens #255

revert(crypt): do not  unlock encrypted devices by default during boot

---

test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh

Use '-m' instead of '-a' to run tests faster and more reliably.
Restores earlier ci functionality and now that dracut regressions are resolved ci can revert 51d06540d.

ci: only install required dracut modules for test-makeroot

---

lsinitrd.sh

as the folder in /usr/lib/dracut/src might just exist; but the file might not.
`lsinitrd` currently checks for directory existence, and assumes the file is just there; but that might not be the case. I have changed the check to explicitly check for the file in that folder. No behaviour change.

fix(lsinitrd): check skipcpio file directly

---

test/container/Dockerfile-OpenSuse-latest

This PR is required to run FULL-SYSTEMD on openSUSE. Test will pass once the CI container gets regenerated.
Reference: https://software.opensuse.org/package/systemd-experimental
Fixes #

ci: install systemd-experimental  into openSUSE container

---

test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-OpenSuse-latest

The change allows the CI to pick up distribution config from the dracut package.
CI should be able to run not only in pristine default configuration, but also in the configuration that the distribution set as the default.
As an example Fedora CI should run tests in hostonly mode (unless specified otherwise).
Without this change some containers (e.g. Void, Ubunut, Arch) has the native dracut package installed and some do not (e.g. Fedora).
Fixes #

ci: do not remove native dracut installation from the test containers

---

man/dracut.8.asc

dracut no longer defaults to gzip. There is a list of compressors and the first available is used. See 9663307c and 693b7a32.
Add a warning about kernel support for gzip decompression, similar to all of the other compressor options.

fix(man): update description of the --gzip option

---

test/TEST-16-DMSQUASH/test.sh
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-OpenSuse-latest
test/test-functions

1./  test: do not force no-hostonly for all test runs
Different distributions and containers might prefer different defaults.
The motivation of this work is to increase test coverage and to run the tests in the same configurations as dracut is used.
2./ test: grab the distro configuration from the host and make it available to the tests
Fix failing test cases by enforcing no-hostonly for those tests cases that need it.   
3./ ci: remove dracut native config that is not compatible with upstream ci from the container                                                                                                            
Fixes #543

test: run ci with distro configuration from the host

---

test/TEST-11-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-17-LVM-THIN/test.sh

Adding modules explicitly is required in hostonly mode as the actual CI continaer host is not using these modules to boot.
Fixes #

ci: improve test LVM, IMSM and LVM-THIN to work in hostonly mode

---

test/TEST-18-UEFI/test.sh

Now that we have hostonly and no-hostonly CI containers, no need to run the same test twice in the same container.
Also, the current approach did not actually work as the second initrd would just overwrite the first one without testing the boot.
No need to add `rootfs-block` module explicitly as it is always included.

test(UEFI): second initrd would just overwrite the first

---

dracut-init.sh
dracut-initramfs-restore.sh
dracut.sh
lsinitrd.sh
modules.d/95squash-erofs/module-setup.sh
modules.d/95squash-squashfs/module-setup.sh
modules.d/99busybox/module-setup.sh
modules.d/99squash/init-squash.sh
modules.d/99squash/module-setup.sh

This pull request adds support for erofs for the 99squash module. For this it first cleans up the special handling needed in dracut.sh, then splits out the squashfs specific code into 95squash-squashfs and, finally adds a new 95squash-erofs module. The "new" 99squash module is designed in a way that it picks an appropriate back end automatically if added directly and none of the back ends is provided. Default is to use squashfs to keep the current behavior.
There are still some small things to do in lsinitrd and dracut-rescue-initramfs. Nevertheless, it would be good to get some feedback about the overall approach.

feat(squash): Add support for erofs

---

.github/workflows/integration.yml

Only map /dev/kvm into the container to be able to use kvm when when running VMs with qemu.

ci: drop privileged container flag to run tests sandboxed

---

dracut.sh

`kernel` is also a name accepted by `grub-mkconfig`.
On Gentoo the kernel is named this way if systemd's `kernel-install` is used.
Fixes #

fix(dracut.sh): account for the kernel being named kernel

---

dracut-functions.sh

With udev 256, there are now directories such as
/dev/disk/by-path/pci-0000:02:00.0-nvme-1-part/ which match here.
In case a nonexisting file/device was passed to get_persistent_dev, it returned the first directory it looked at because both have maj:min 0:0. This accidental conversion from garbage to a sensible looking path leads to weird behaviour later.
Instead of filtering out directories explicitly switch the check to only return block devices, which also takes care of the character special /dev/mapper/control.

fix(dracut-functions.sh): Only return block devices from get_persistent_dev

---

dracut-init.sh

dracut-install calls `ldd` to resolve dependencies, but when the `--sysroot` option is used, `ldd` is not performing the search within the sysroot directory. To fix this issue, the `LD_LIBRARY_PATH` variable needs to be properly set to the directories containing shared libraries within the specified sysroot directory.
E.g., running dracut with `--sysroot` produces an initrd without the required systemd shared libraries when the version between the host system and the sysroot directory differs:
```
localhost:~ # ldd /.snapshots/9/snapshot/usr/lib/systemd/systemd | grep libsystemd
libsystemd-core-256.so => not found
libsystemd-shared-256.so => not found
localhost:~ # export LD_LIBRARY_PATH=/.snapshots/9/snapshot/usr/lib64/systemd
localhost:~ # ldd …
```

fix(dracut): ldd output borked with `--sysroot`

---

dracut-functions.sh
dracut.sh

If the installed kernel has no initrd support, skip the image creation.
Fixes #

support kernels without initrd

---

dracut.sh

Follows up on:
- https://github.com/dracut-ng/dracut-ng/pull/520
- https://github.com/dracut-ng/dracut-ng/pull/541
And fixes:
- https://github.com/dracut-ng/dracut-ng/issues/378
Note #520 contains a fix for the `check_kernel_config` function and should be merged first.
Closes: https://github.com/dracut-ng/dracut-ng/issues/378
Fixes #378

fix(dracut.sh): use only compressor that kernel supports

---

src/install/dracut-install.c

With DRACUT_LDD='', let's fallback to default ldd. Better safe than sorry.
Fixes #

fix(dracut-install): refuse empty DRACUT_LDD environment variable

---

modules.d/06rngd/module-setup.sh
modules.d/06rngd/rngd.service
modules.d/06rngd/sysconfig

Note: this is dependent Fedora / RH rngd service file containing
`ExecStart=/usr/sbin/rngd -f $RNGD_ARGS`
Use system service file, but ship modified args to drop the user change.
There's no reason to keep a copy of `rngd.service`; there shouldn't be any modifications.
In case there are args stored in a separate file (Fedora and alike), it needs to be supplied too, but without the option to change the user.

fix(rngd): install system service file

---

modules.d/80test-makeroot/module-setup.sh
modules.d/80test/module-setup.sh

Always install Linux kernel modules regardless of the value of hostonly.

fix(test): always install kernel modules

---

modules.d/95nfs/module-setup.sh

as those paths are used by bootc instead of the /etc ones.
Handle  /usr/lib/{passwd,group} configs additionally to /etc/ variants in nfs module.

fix(nfs): include also entries from /usr/lib/{passwd,group}

---

modules.d/95squash-erofs/module-setup.sh

Option --exclude-path from mkfs.erofs requires a path relative to the source of the image. Otherwise the path won't be excluded resulting in a slightly larger (~1M) initrd.
Fixes: ebc9e84d ("feat(squash): add module 95squash-erofs")

fix(95squash-erofs): properly exclude $squashdir

---

modules.d/00systemd/module-setup.sh
modules.d/01systemd-coredump/module-setup.sh
modules.d/01systemd-pstore/module-setup.sh
modules.d/01systemd-resolved/module-setup.sh
modules.d/01systemd-timesyncd/module-setup.sh

and also use proper variables for the paths.
The new systemd reads from both /etc and /usr/, so to accomodate this, I've added new paths to install configs from (I probably haven't covered all). This changes only hostonly behaviour; uses global variables:
```
set_global_var "systemd" "systemdutildir" "/lib/systemd:/lib/systemd/systemd-udevd" "/usr/lib/systemd:/usr/lib/systemd/systemd-udevd"
set_global_var "systemd" "systemdutilconfdir" "/etc/systemd"
```
(also defined in the config `/usr/lib/dracut/dracut.conf.d/01-dist.conf`)
Ref: https://issues.redhat.com/browse/RHEL-32506
```bash
[root@localhost ~]# lsinitrd | grep system.conf
-rw-r--r--   1 root     root         2342 Jun  2 00:00 usr/lib/systemd/system.conf
~ lsinitrd | grep system.conf
-rw-r--r--   1 root     root         2124 Mar 10 …
```

feat(systemd*): Include systemd config files from /usr/lib/systemd

---

modules.d/90crypt/module-setup.sh

Without dm_crypt Linux module, the dracut module will not be fully functional.

fix(crypt): install dm_crypt module in non-hostonly mode as well

---

test/TEST-14-IMSM/test.sh

This test is testing mdraid, do not include dmraid into the same initrd that is being tested as it is unnecessary.
Fixes #

test(ISMS): only include mdraid into the initrd under test

---

src/install/dracut-install.c
tools/test-github.sh

The intention of this PR is to enforce that on all CI containers C code builds without any warnings.
This PR intentionally does not enforce the same for normal builds.
Follow-up to https://github.com/dracut-ng/dracut-ng/commit/d71bec4aa444d92820e428c0629d0e75e268c815 (https://github.com/dracut-ng/dracut-ng/pull/479)
Fixes #

chore: treat compilation warning as errors

---

test/container/Dockerfile-alpine

Similarly to Fedora, this PR enables hostonly by default for Alpine Linux CI container.
This PR installs additional packages to the
Alpine container that other Linux test containers already have.
This PR removed extra post steps from the container that are not necessary.
Fixes #

ci(alpine): install dracut to enable native dracut configuration

---

test/TEST-04-FULL-SYSTEMD/test-init.sh
test/TEST-04-FULL-SYSTEMD/test.sh

Remove packaging and distribution specific systemd service files.
No need to explicitly check if /usr is mounted as without it Switch Root service would fail with the following error:
'Failed to start initrd-switch-root.service - Switch Root.'

test(FULL-SYSTEM): simplify and make it easier to maintain

---

modules.d/95udev-rules/module-setup.sh

Follow-up to https://github.com/dracut-ng/dracut-ng/pull/511  - specifically to https://github.com/dracut-ng/dracut-ng/pull/511#issuecomment-2258395025 .

fix(udev-rules): install dropins for udev.conf

---

modules.d/00systemd/module-setup.sh

These targets are installed in the systemd-cryptsetup dracut module.

fix(systemd): remove duplicate systemd cryptsetup targets

---

test/TEST-05-SYSTEMD-INITRD/test.sh

Call the test_dracut function and omit the `test` module instead of repeating the logic.
CC @PrincessDoreena (great test BTW!).
Fixes #

test(SYSTEMD-INITRD): call test_dracut instead of repeating it

---

modules.d/90crypt/module-setup.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh

Make `systemd-cryptsetup` a dependency of the `crypt` module when systemd dracut module is included.
Improve tests with crypt dracut module to work in hostonly mode. Enable running these test both in hostonly and non-hostonly mode.
Fixes #563

fix(dracut-systemd): include systemd-cryptsetup module when needed

---

test/container/Dockerfile-Gentoo

See for syntax rules
https://docs.docker.com/reference/build-checks/from-as-casing/ .
Fixes #

ci(Gentoo): fix docker warning

---

modules.d/99base/init.sh
modules.d/99base/module-setup.sh

Not needed since https://github.com/dracut-ng/dracut-ng/commit/348baca3e401f2526b0f936cb172874f4bbe9dcd
Fixes #

fix(base): remove undocumented real_init, realinitpath and rd.distroinit

---

modules.d/01fips-crypto-policies/fips-crypto-policies.sh
modules.d/01fips-crypto-policies/module-setup.sh

(Supersedes #575, @t184256 opened that in my absence to speed up the review process; I've made the change requested in https://github.com/dracut-ng/dracut-ng/pull/575#pullrequestreview-2231750738)
For a system that uses crypto-policies to be switched to FIPS mode correctly, it needs to be
- booted with `fips=1` on the kernel command line
- switched to the FIPS crypto-policy (or a policy derived from it)
- have the fips dracut module enabled
On older systems, there were additional steps, for example, creating `/etc/system-fips`.
We have repeatedly seen inconsistencies between those different toggles, either because the user space tooling to switch between those does not (for reliability, maintainability, and compliance reasons) undo some of the steps it does when disabling FIPS mode, or …

feat(fips-crypto-policies): make c-p follow FIPS mode automatically

---

modules.d/00systemd/module-setup.sh

loadkeys is installed by `10i18n` dracut module.
This resolves the following error in tests where `10i18n` dracut module is not included (e.g. TEST-5).
```
[FAILED] Failed to start Virtual Console Setup.
```
Fixes #

fix(systemd): systemd-vconsole-setup has a dependency on loadkeys

---

modules.d/00systemd/module-setup.sh
modules.d/90crypt/module-setup.sh
modules.d/90systemd-cryptsetup/module-setup.sh
modules.d/98dracut-systemd/module-setup.sh

After d0f8fde5668cfd7fda1d15824e268b4949b4fd04 regressed module dependency check, it made the tree vulnerable to a module dependency cycle. 
8907ba124e9dcd57049c2ccb4fd20b98b3bd83c2 introduced a cycle in the module dependency. 
Now that the module dependency check is fixed, the cycle is detected and the CI is failing.
This PR resolves the cycle by reverting the offending commit and instead adds an alternative fix that was originally proposed in the PR that introduced the cycle.
Also moves cryptsetup-pre.target from systemd dracut module to systemd-cryptsetup dracut module.
Fixes #563

fix(systemd-cryptsetup): install cryptsetup-pre.target

---

test/TEST-05-SYSTEMD-INITRD/test.sh

Separate systemd-based initrd out from the rest of the test infrastructure to make it easier to check (e.g. by passing -v) what is included in this minimal initrd.
Explicitly verify that dracut systemd services are not included in this test.
This test produces initrd that is comparable design to the systemd based initrd produced by mkosi or mkinitcpio.
Copy some additional tests steps from FULL-SYSTEMD and include it in this test as well.
Fixes #

test(SYSTEMD-INITRD): kernel-independent systemd-based initrd

---

modules.d/01systemd-networkd/module-setup.sh
modules.d/01systemd-networkd/networkd-config.sh

Renames the default network file so it has 4 leading 'z', to make it as unlikely as possible for it to be anything but the last file, even if the user has files not following the common naming scheme of "00-abc.network".
Fixes #618

fix(systemd-networkd): make sure default network is always last

---

modules.d/00systemd/module-setup.sh
modules.d/01systemd-ask-password/module-setup.sh

Revert 6b095274fb935ffb7639d1ea7e51f9bd0f487726.
Enable systemd-vconsole-setup.service always when it is avaiable as it usually gets triggered by udev rules anyways.
Fixes #620

revert(systemd): trigger systemd-vconsole-setup.service only on demand

---

test/container/Dockerfile-Debian
test/container/Dockerfile-Ubuntu

Increase test coverage. Some of the newly added packages are needed to to install some dracut modules and are already installed for other CI containers.
Fixes #

ci: add more packages to Debian and Ubuntu containers

---

modules.d/01systemd-networkd/networkd-run.sh

The basename tool was not listed in the requirements and is also not needed.
Also see https://github.com/dracutdevs/dracut/commit/4c216b1db6a86373549e13b60250a7fcf94417b9

fix(systemd-networkd): Remove basename dependency

---

.github/workflows/integration.yml
docs/HACKING.md
test/test-functions
tools/test-github.sh

Set 'rd.debug' for all tests  in 'V=2' mode to make it more verbose than 'V=1' test mode.
Fixes #

test: document and fix extra verbose mode (V=2)

---

test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh

'-m network' does not really work as it is not able to include the actual networking backend as [`check_module`](https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/40network/module-setup.sh#L20) call with always fail.
Fixes #

test: network dracut package needs to be added with '-a'

---

modules.d/00systemd/module-setup.sh
test/TEST-40-NBD/test.sh

- fix(systemd): /sbin/init is not required inside initrd
- fix(systemd): do not set unused target as the default 
- test(NBD): fix the way rootfs is built for test
Fixes #

fix(systemd): remove steps not required inside initrd

---

modules.d/95udev-rules/module-setup.sh

These rules are already present in the systemd dracut module, see https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/00systemd/module-setup.sh#L147
Fixes #

fix(udev-rules): remove systemd-specific rules

---

test/TEST-01-BASIC/create-root.sh
test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/create-root.sh
test/TEST-02-SYSTEMD/test.sh
test/container/Dockerfile-Arch
test/container/Dockerfile-OpenSuse-latest
test/test-functions

Default fstype (when test allows it) is now xfs for Arch and btrfs for openSUSE.   
Tested with the following fstypes:
- ext2
- ext3
- ext4
- btrfs
- jfs
- xfs
XFS filesystem labels can be at most 12 characters long, so move the test case for the '  rdinit=/bin/sh' label to TEST-02 instead and keep TEST-01 simple.
XFS filesystem must be larger than 300MB.
Fixes #

test(BASIC): allow to run the test with various fstypes

---

test/TEST-04-FULL-SYSTEMD/test.sh

i18n is not longer required after 238378ad2b7367900a0050bb9fc5b9eab5294cba.
Fixes #

test(FULL-SYSTEM): remove non-systemd dracut modules from the test

---

test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-Gentoo
test/container/Dockerfile-Ubuntu
test/container/Dockerfile-alpine

Add plymouth to the following containers:
- Fedora
- Gentoo
- Alpine
Fixes #
CC @pvalena @AndrewAmmerlaan

ci: test plymouth dracut module in more containers

---

modules.d/80test-root/module-setup.sh

This PR enables CI to run faster by default (V=1).
When debugging (V=2) debug module will be included as before.
Follow-up to https://github.com/dracut-ng/dracut-ng/pull/607 .
Fixes #
CC @bdrung

feat(test-root): only include debug module if V is set to 2

---

dracut-functions.sh

as the path might be f.e. /dev/disk/by-partlabel/EFI\x20System\x20Partition
which would produce Warning 'grep: warning: stray \ before x' in get_maj_min
Escape the \ to preserve it in the path when passing to grep.
Resolves: !505

fix(dracut-functions): allow for \ in get_maj_min file path

---

src/install/dracut-install.c

When using `--sysrootdir` argument, we cannot assume `fulldstpath` and `fullsrcpath` always start with `sysrootdir`. When `dracut_install` is called on the `destination` directory, this can result in a passing pointer which is often beyond the valid buffer.
This pull request checks the handled path and only if it starts with `sysrootdir `, the pointer is incremented by the `sysrootdirlen` to get a path relative to the `sysrootdir`
Arguably current behaviour is dangerous, since if the passed buffer is shorter than `sysrootdirlen`, the resulting pointer, which is passed further, is to the random memory location.
This can be seen in debug logs when `resolve_deps('` log is either empty or has random garble printed.
Check the path for `sysrootdir` before incrementing the pointer.
- [x ] I have …

fix(dracut-install): do not assume handled path starts with sysrootdir

---

src/install/dracut-install.c

This pull request fixes incorrect handling of `--sysrootdir` argument when passed value trails with `/`
Changes
check passed `sysrootdir` for trailing `/` and decrement `sysrootdirlen` by `1` if `/` is detected.
Checklist
[ x] I have tested it locally
[x ] I have reviewed and updated any documentation if relevant
[ x] I am providing new code and test(s) for it
Fixes #
https://github.com/dracut-ng/dracut-ng/issues/547

fix(dracut-install): handle correctly sysrootdir with trailing '/'

---

src/install/dracut-install.c

Fix the following build error with clang
```
src/install/dracut-install.c:1643:58: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
1643 | static void find_suppliers_for_sys_node(struct kmod_ctx *ctx, Hashmap *suppliers, const char *node_path_raw,
|                                                          ^
1 error generated.
```
Fixes #

chore(dracut-install): fix clang build

---

test/container/Dockerfile-alpine

CI container to reproduce clang build issues.
Fixes #

ci(alpine): use clang instead of gcc for more test coverage

---

modules.d/40network/module-setup.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh

If the meta module is included via `-m` `check_module` fails unexpectedly.
Call `module_check` directly instead of `check_module`.
Use this as an opportunity to refactor the network module code for improved readability.
From the CI test log it can now be observed that some tests are switched to `network-manager` from `network-legacy` (e.g. on arch) when `USE_NETWORK` is set to `network`.
This change expose some additional issue with the tests themselves. For some tests we need to continue to force network-legacy for server as most test server code not yet support booting into systemd and instead it just starts the server code from /sbin/init.
Fixes #634

fix(network): handle '-m network'

---

modules.d/01fips/fips.sh
modules.d/01fips/module-setup.sh

Kernel integrity check in FIPS module is incompatible with UKIs as neither /boot/vmlinuz-`uname-r` nor /boot/.vmlinuz-`uname-r`.hmac are present. UKI is placed to $ESP\EFI\Linux\<install-tag>-<uname-r>.efi and if a .hmac file is present next to it, it is possible to do similar check.
Note, UKIs have a 'one size fits all' command line and 'boot=' is not expected to be set. Luckily, if the UKI is systemd-stub based then we can expect 'LoaderDevicePartUUID' variable containing PARTUUID of the ESP to be set. Mount it to /boot using the existing logic.
Support for UKI integrity checking added to the FIPS module.
- [ X ] I have tested it locally
- [ - ] I have reviewed and updated any documentation if relevant
- [ X ] I am providing new code. Testing this outside of a real UKI based environment …

feat(fips): add support for UKIs

---

dracut.sh
man/dracut.8.asc
shell-completion/bash/dracut

Add --extra-confdir option 
When generating kdump's initrd, we want to keep [omit_]dracutmodules empty and let kdump to handle the modules. And we don't want to affect the first kernel's initrd, so we cannot place our conf file to /etc/dracut.conf.d or /usr/lib/dracut/dracut.conf.d.
This patch adds a new option to allow user to add an extra configuration directory to use *.conf files from.
After that, kdump will use --extra-confdir /usr/lib/kdump/dracut.conf.d to apply its own dracut conf.
See also:
https://github.com/rhkdump/kdump-utils/issues/11
https://github.com/rhkdump/kdump-utils/pull/31
- [*] I have tested it locally
- [*] I have reviewed and updated any documentation if relevant
- [*] I am providing new code and test(s) for it

feat(dracut.sh): add --add-confdir option

---

src/install/dracut-install.c

Flipping `S_IFMT` gives the file mode bits.

refactor(dracut-install): simplify open() call in cp()

---

dracut.sh

Follow-up fix for https://github.com/dracut-ng/dracut-ng/commit/6107f5e54fb82f1c00285a4cc709b04f29eee460
CC @licliu 
Fixes #

fix: typo in variable name

---

dracut.sh

Unlike ordinary binaries, kernel module will be unusable if stripped with "-p". Fix this by always use "-g" only.
So far it didn't cause many issues since most kernels have their modules signed or compressed so this is skipped.
Signed-off-by: Kairui Song <kasong@tencent.com>
Fixes #

fix(dracut): don't apply aggressive strip to kernel modules

---

dracut.conf.d/50-uki-virt.conf.example
test/TEST-18-UEFI/test.sh

This is an example configuration for a 'unified kernel image'.
The key benefit of a unified kernel is that its secure boot signature covers the initrd and cmdline contents, allowing a trustworthy measured boot process with attestation, which is not practical with locally generated initrds/cmdlines.
The initrd in this example only needs a very small set of block driver modules present, in order to be usable across KVM, Hyper-V and Xen hypervisors which will cover essentially all common public and private clouds.
Credit for most of this work goes to  @vittyvk  and @trungams . The example is not intended to be the exact latest copy that is used downstream. Instead the example is meant to be a superset of the downstream use-cases to provide a form of documentation of dracut (comments in the …

feat: config example for cloud provider uki vm

---

dracut.sh

This will ensure that 'dracut --list-modules' works well in a container.
Fixes #

fix(dracut): --list-modules should imply --no-kernel as well

---

modules.d/01systemd-initrd/module-setup.sh

Make sure /etc/initrd exist without depending on the base module.
Test SYSTEMD-INITRD confirms no regression as this tests now no longer includes the base module and it still passes the boot tests with systemd (hence the perf tag).
Fixes #

perf(systemd-initrd): do not depend on base module

---

modules.d/95hwdb/module-setup.sh

"$udevconfdir"/hwdb.bin already grabs /etc/udev/udev.hwdb in hostonly mode.
Fixes #

fix(hwdb): only install /etc/udev/udev.hwdb in hostonly mode

---

test/container/Dockerfile-alpine
test/container/Dockerfile-arch
test/container/Dockerfile-debian
test/container/Dockerfile-fedora
test/container/Dockerfile-gentoo
test/container/Dockerfile-opensuse
test/container/Dockerfile-ubuntu
test/container/Dockerfile-void

Add swtpm for TPM emulation
Also remove unused interactive debugging tools (vi, strace, tcpdump, wget, less)
Fixes #

ci: add swtpm for TPM emulation

---

dracut-functions.sh
dracut.sh
modules.d/99base/module-setup.sh

Currently, dracut adds a systemd dropin that sets an infinite timeout _only_ for the underlying persistent devices of each host device that must be active in the initrd. E.g.:
```
localhost:~ # dracut -f --stdlog 3 --install "/mnt" --mount "/dev/sda1 /mnt btrfs rw,relatime"
localhost:~ # lsinitrd | grep timeout.conf
-rw-r--r--   2 root     root            0 Oct 28 14:21 etc/systemd/system/dev-disk-by\x2duuid-0d1b24c2\x2df112\x2d48ef\x2d8442\x2d1001cffc92f0.device.d/timeout.conf
localhost:~ # ls -l /dev/disk/by-uuid/0d1b24c2-f112-48ef-8442-1001cffc92f0
lrwxrwxrwx 1 root root 10 Oct 28 11:43 /dev/disk/by-uuid/0d1b24c2-f112-48ef-8442-1001cffc92f0 -> ../../sda1
```
It can be verified in the emergency shell:
```
sh-5.2# systemctl show --property JobRunningTimeoutUSec …
```

fix(dracut): rework timeout for devices added via --mount and --add-device

---

man/dracut.cmdline.7.adoc
modules.d/90dmsquash-live/dmsquash-live-root.sh

From: @gmileka
Dracut allows the creation of a LiveOS using a read-only squashfs and a read-write overlay on top.
If the read-write overlay is backed by a ramdisk, Dracut halts and prompts the user to confirm whether to continue or not.
This interaction during the boot process is not desired in all cases.
This change introduces a new flag (rd.live.overlay.nouserconfirmprompt) that when defined, it suppresses the prompt and allows the boot process to continue to completion without user interation.
There is no impact to existing configurations and their associated behavior. The new behavior only takes effect only when the new switch is explicitly defined by the image build as a kernel parameter.

feat(dmsquash-live): add support for rd.live.overlay.nouserconfirmprompt

---

man/dracut.8.adoc

These are common footguns. We should do a better job warning the users against these usually untested configurations.
CC @ianw 
Fixes #

docs: warn against the usage of -n, -o, -d

---

modules.d/95nvmf/module-setup.sh

I do not see anywhere where bash would be required for the `nvmf` module.
@bdrung @mwilck what do you think ? Am I missing something ? 
Fixes #

feat(nvmf): enable other shells (dash) not just bash

---

modules.d/99base/module-setup.sh

This fallback is no longer needed after the introduction of the shell-interpreter dracut module.
Fixes #

fix(base): remove fallback for shell selection

---

modules.d/00systemd/module-setup.sh

Following crash seen on the CI intermittently 
```
[    4.373065] systemd[1]: Failed to open libbpf, cgroup BPF features disabled: Operation not supported
systemd[1]: Failed to open libbpf, cgroup BPF features disabled: Operation not supported
[    4.404177] systemd[1]: Assertion 'close_nointr(fd) != -EBADF' failed at src/basic/fd-util.c:75, function safe_close(). Aborting.
```
Related bug found in the Fedora/RedHat bug database  - https://bugzilla.redhat.com/show_bug.cgi?id=2084955#c34
> systemd dlopens libbpf, dracut fails to add systemd's dependency on libbpf in initrd, 
> but dracut-network adds it to initrd, because it pulls in /usr/sbin/ip, which is linked against libbpf.so.0.
Fixes #

fix(systemd): systemd dlopens libbpf

---

test/modules.d/80test-root/module-setup.sh

Include an existing dracut module instead of attempting to reimplement it.
Fixes #

test(test-root): include terminfo dracut module

---

modules.d/98dracut-systemd/dracut-cmdline-ask.service
modules.d/98dracut-systemd/dracut-cmdline.service
modules.d/98dracut-systemd/dracut-emergency.service
modules.d/98dracut-systemd/dracut-initqueue.service
modules.d/98dracut-systemd/dracut-mount.service
modules.d/98dracut-systemd/dracut-pre-mount.service
modules.d/98dracut-systemd/dracut-pre-pivot.service
modules.d/98dracut-systemd/dracut-pre-trigger.service
modules.d/98dracut-systemd/dracut-pre-udev.service
modules.d/98dracut-systemd/emergency.service
modules.d/98dracut-systemd/module-setup.sh

Modern systems have /usr merged and `/bin` pointing to `/usr/bin`. So install all `dracut-*` scripts into `/usr/bin` instead of `/bin`.
Fixes #

feat(dracut-systemd): install dracut-* into /usr/bin

---

dracut-init.sh

systemd-sysuser dracut module uses inst_sysusers function to install configuration files. These configuration files are named differently in Gentoo, which impacts upstream Gentoo CI as well.
Partially fixes https://github.com/dracut-ng/dracut-ng/issues/274
Based on Gentoo downstream patch https://github.com/gentoo/gentoo/blob/master/sys-kernel/dracut/files/dracut-103-acct-user-group-gentoo.patch by Nowa Ammerlaan <nowa@gentoo.org>
This PR is required to restore green CI.
CC @Nowa-Ammerlaan 
Fixes #274

fix(systemd-sysuser): add support for Gentoo

---

test/TEST-70-ISCSI/test.sh
test/run-qemu

Several architectures do not support the qemu option `-acpitable`. Skip the `root=ibft` in this case.
Fixes #

test(ISCSI): skip root=ibft if qemu -acpitable is not supported

---

test/TEST-61-MULTINIC/client-persistent-lan0.link
test/TEST-61-MULTINIC/client-persistent-lan1.link
test/TEST-61-MULTINIC/client-persistent-lan2.link
test/TEST-61-MULTINIC/client-persistent-lan254.link
test/TEST-61-MULTINIC/client-persistent-lan255.link
test/TEST-61-MULTINIC/client-persistent-lan98.link
test/TEST-61-MULTINIC/client-persistent-lan99.link
test/TEST-61-MULTINIC/client.link
test/TEST-61-MULTINIC/test.sh
test/TEST-70-ISCSI/client-persistent-lan0.link
test/TEST-70-ISCSI/client-persistent-lan1.link
test/TEST-70-ISCSI/client.link
test/TEST-70-ISCSI/test.sh
test/TEST-71-ISCSI-MULTI/client-persistent-lan0.link
test/TEST-71-ISCSI-MULTI/client-persistent-lan1.link
test/TEST-71-ISCSI-MULTI/client.link
test/TEST-71-ISCSI-MULTI/test.sh

TEST-70-ISCSI fails on Ubuntu s390x because the network device is named `enc0` instead of `enp0s1`:
```
CLIENT TEST START: NBD root=nbd:IP:port
[...]
[   36.084991] virtio_net virtio2 enc0: renamed from eth0
```

test: use persistent names for network devices

---

test/TEST-41-FULL-SYSTEMD/test.sh

The qemu option `-smbios` is not supported on most architectures. Therefore `TEIT-41-FULL-SYSTEMD` will fail.
Fixes #1213

test(FULL-SYSTEMD): skip encrypted root if qemu -smbios is not supported

---

test/TEST-41-FULL-SYSTEMD/test.sh

The Debian/Ubuntu package runs the FULL-SYSTEMD test without dracut-network installed. Therefore the test fails due to the missing `systemd-network-management` module:
```
TEST: Full systemd serialization/deserialization test with /usr mount
dracut[E]: Module 'systemd-network-management' cannot be found.
```
Fixes: 75f3a191b675 ("test(FULL-SYSTEMD): when systemd-networkd is available, install it")

test(FULL-SYSTEMD): skip systemd-network-management if missing

---

.github/workflows/release.yml
tools/release.sh

Create release commit on relese branch automatically, but leave the rest of the release creation process up to the project admins to allow manual review and intervention.
We do not have a valid email address for the release automation, so let's make it obvious that it is just a placeholder email address.
@bdrung @Conan-Kudo

fix(release): tagging and release generation is no longer automated

---

modules.d/99base/dracut-lib.sh
test/TEST-10-BASIC/test.sh
test/TEST-11-USR-MOUNT/test.sh
test/TEST-12-UEFI/test.sh
test/TEST-20-STORAGE/test.sh
test/TEST-23-IMSM/test.sh
test/TEST-26-ENC-RAID-LVM/test.sh
test/TEST-30-DMSQUASH/test.sh
test/TEST-40-SYSTEMD/test.sh
test/TEST-41-FULL-SYSTEMD/test.sh
test/TEST-42-SYSTEMD-INITRD/test.sh
test/TEST-43-KERNEL-INSTALL/test.sh
test/TEST-60-NFS/test.sh
test/TEST-61-MULTINIC/test.sh
test/TEST-62-BONDBRIDGEVLAN/test.sh
test/TEST-70-ISCSI/test.sh
test/TEST-71-ISCSI-MULTI/test.sh
test/TEST-72-NBD/test.sh
test/TEST-80-GETARG/test.sh
test/TEST-81-SKIPCPIO/test.sh
test/TEST-82-DRACUT-CPIO/test.sh
test/test-functions

To make all tests more robust, use `set -e` in all tests. Then the `|| return 1` constructs can be removed.

test: use "set -e" in all tests

---

test/TEST-60-NFS/test.sh
test/TEST-61-MULTINIC/test.sh
test/TEST-62-BONDBRIDGEVLAN/test.sh
test/TEST-70-ISCSI/test.sh
test/TEST-71-ISCSI-MULTI/test.sh
test/TEST-72-NBD/test.sh
test/test-functions

The variable `TEST_FSTYPE` will be needed to construct `TEST_DESCRIPTION`.
So define `TEST_FSTYPE` in the respective tests before defining `TEST_DESCRIPTION`.

test: define default network/fstype in the respective tests

---

modules.d/90btrfs/module-setup.sh

btrfs-progs also includes the program btrfstune; can we please include this in dracut?
This controls a few things that require the filesystem to be unmounted, so having it in dracut would be useful for anything that affects the root partition. My use case was that I needed the block group tree to be enabled for my root partition, but as btrfstune wasn't there I couldn't use the rescue console for this.
Thanks

btrfs: also install btrfstune

---

modules.d/60systemd-sysusers/module-setup.sh

dracut prints 20 lines when creating users and groups even with `--quiet` option. Sample output:
```
Creating group 'nobody' with GID 65534.
Creating group 'audio' with GID 997.
Creating group 'disk' with GID 995.
Creating group 'input' with GID 994.
Creating group 'kmem' with GID 993.
Creating group 'kvm' with GID 992.
Creating group 'lp' with GID 991.
Creating group 'optical' with GID 990.
Creating group 'render' with GID 989.
Creating group 'sgx' with GID 988.
Creating group 'storage' with GID 987.
Creating group 'tty' with GID 5.
Creating group 'uucp' with GID 986.
Creating group 'video' with GID 985.
Creating group 'users' with GID 984.
Creating group 'systemd-journal' with GID 983.
Creating user 'root' (Super User) with UID 0 and GID 0.
Creating user 'nobody' (Kernel Overflow User) …
```

fix(systemd-sysusers): silence "Creating " on stderr

---

modules.d/01systemd-integritysetup/module-setup.sh

Required since https://github.com/systemd/systemd/commit/810708f4b820543b8585a36e84ccca4bc5b18fee

feat(systemd-integritysetup): add remote-integritysetup.target

---

test/container/Dockerfile-fedora

Fix the following error message on Fedora Rawhide .
```
fips-mode-setup: command not found
```
CC @LaszloGombos @Conan-Kudo

ci(fedora): always use update-crypto-policies to enable fips

---

modules.d/90mdraid/module-setup.sh

We use `command -v` to find mdadm binary on the system anyway, so it makes no sense to call it using the full path.
Bug: https://bugs.gentoo.org/951284

fix(mdraid): do not call mdadm with full path

---

modules.d/90multipath/module-setup.sh

Commit 1e802f15f creates a default multipath.conf file with "find_multipaths strict" when run in non-hostonly mode if there are no multipath devices and no multipath.conf. Unfortunately for systems that want to use mpathconf to create a multipath.conf file (e.g. Fedora and Centos) either through multipathd-configure.service or multipathd.sh, this default file keeps that from occurring. To make sure mpathconf is called to create the config file, do not install a default config file if mpathconf is installed.
Fixes: ("fix(multipath): include module with find_multipaths strict")
Fixes #509
CC: @pvalena @LaszloGombos @mwilck @jlebon

fix(multipath): skip default multipath.conf with mpathconf

---

test/container/Dockerfile-fedora

Add systemd-container to make sure portablectl is installed.
See https://src.fedoraproject.org/rpms/systemd/c/49ec9f3286e6c18e48f3ee3a08da950d0113f853?branch=rawhide portablectl and importctl are moved to systemd-container (rhbz#2345551)
This change is required to restore green CI.
It seems the Fedora container is not actively maintained by the Fedora team and it seems this adds a bit of a burden on non-Fedora contributors. 
CC @pvalena @keszybz @lnykryn  
Fixes #

ci(Fedora): make sure portablectl is installed

---

modules.d/00systemd/module-setup.sh
modules.d/35network-legacy/ifup.sh
modules.d/95ssh-client/module-setup.sh
modules.d/99base/module-setup.sh

1. chore(network-legacy): no need to call chmod on ifup.sh
This is a small optimization, with the goal of avoiding calling chmod for a file that is already guaranteed to be an executable.
2. perf(base): move the chmod dependency from base to systemd
base dracut module no longer requires chmod.
Fixes #

perf(base): remove the chmod dependency from base 

---

.github/labeler.yml
modules.d/45simpledrm/module-setup.sh

Plymouth doesn't always show a splash screen if DRM drivers are installed in initrd.
Provide a `simpledrm` module that only installs the SimpleDRM module and the potentially needed privacy screen providers. This `simpledrm` module is a subset of the `drm` module. It could be used instead of `drm` to avoid pulling in drivers like amdgpu, nouveau, or nvidia-drm.
Bug-Ubuntu: https://launchpad.net/bugs/2105377

feat: add simpledrm module (as subset of drm module)

---

modules.d/00systemd/module-setup.sh

Introduced in https://github.com/systemd/systemd/commit/0bdd5ccc8145af8dae9779751d3e7a34c4fa6aa5
Used internally in fstab-generator (new `x-systemd.validatefs` mount option) and gpt-auto-generator: https://github.com/systemd/systemd/commit/f872373a26dcaa0818b49220abfe35611d12fa82

feat(systemd): add new systemd-validatefs@.service

---

dracut-init.sh

On usrmerge systems, `/lib` is a symlink to `/usr/lib`, so the real path of the kernel directory is `/usr/lib/modules/<kver>`. The issue on these systems is that a kernel module can be added to the initrd (via dracut-install) by different dracut modules using both paths, and that causes libkmod to display the following type of errors in the middle of the dracut build:
```
libkmod: ERROR: kmod_module_new_from_path: kmod_module 'nvidia' already exists with different path: new-path='/lib/modules/6.14.1-1-default//weak-updates/updates/nvidia-open-driver-G06-signed-570.133.07/nvidia.ko.zst' old-path='/usr/lib/modules/6.14.1-1-default/weak-updates/updates/nvidia-open-driver-G06-signed-570.133.07/nvidia.ko.zst'
libkmod: ERROR: kmod_module_parse_depline: ctx=0x560bbacad8f0 …
```

fix(dracut-init): assign real path to srcmods

---

modules.d/90crypt/module-setup.sh

Not only are the specific encryption modules not being installed on s390/s390x in non-hostonly mode, but also it's failing the detection of the kernel modules needed to decrypt PAES-encrypted volumes in hostonly mode via dmsetup. So, since the increase in size is not that much (~ 150K), always add all the drivers under s390/crypto in this architecture.

fix(crypt): always install s390 crypto modules

---

.github/workflows/container-extra.yml
.github/workflows/integration-extra.yml
.github/workflows/manualtest.yml
test/container/Dockerfile-azurelinux

Add Dockerfile for Azure Linux.
The Azure Linux Dockerfile is mostly based off the Fedora version without the unavailable packages.
`TEST-43-KERNEL-INSTALL` is failing with the following message, but I have not figured out why
```
Failed to chase path /usr/lib/modules/6.6.78.1-3.azl3/vmlinuz for kernel image file specified via command line, ignoring: No such file or directory
```
Fixes #

test: add container for Azure Linux

---

modules.d/99base/module-setup.sh

5bf724f & 41f9e8f, have exposed the misuse of the ID= parameter in initrd-release and its links when using init.sh.
Fixes #

fix(base): only set ID to dracut if systemd is not used

---

modules.d/06rngd/module-setup.sh

require_binaries checks for an executable binary, but systemd service files are usually not executable nor binary.
resolves an issue discovered on gentoo where the rngd module would refuse to be included due to a missing file that does in fact exist
Fixes #

fix(rngd): do not check for +x perms

---

modules.d/99systemd-sysusers/module-setup.sh

systemd-sysuser module should be orders afer all modules that depends on it.
This is to make sure that all inst_sysusers calls are in place before systemd-sysusers is called.
Not only this fixes  tpm2-tss module, this should also fix https://github.com/dracut-ng/dracut-ng/issues/1199
CC @pyromaniac2k
Fixes #

fix(systemd-sysusers): make sure tss user for tpm2 is created

---

test/container/Dockerfile-opensuse

arm64 CI started to fail with cpio binary missing.
See https://github.com/dracut-ng/dracut-ng/actions/runs/14553893920
Fixes #

ci(opensuse): make sure cpio is explicitelly installed

---

test/container/Dockerfile-azurelinux

tar is required to download dracut source code before a build.
See https://github.com/dracut-ng/dracut-ng/actions/runs/14553898345
CC @trungams @LaszloGombos @Conan-Kudo

ci(azurelinux): make sure tar is installed

---

dracut.sh

If dracut fails to build the initrd image or EFI binary for any reason (e.g., if `cp` fails because there is no space left on the device), it removes the existing output file before exiting, which may result in an unbootable system. Instead of copying the initrd image directly to the output, copy it alongside it to the same output directory, and if the copy succeeds, replace it.

fix(dracut): protect existing output file against build errors

---

test/container/Dockerfile-arch
test/container/Dockerfile-azurelinux
test/container/Dockerfile-debian
test/container/Dockerfile-fedora
test/container/Dockerfile-gentoo
test/container/Dockerfile-opensuse

As requested in #1260.
systemd's fido2 feature is used for testing because nothing else is likely to pull in libfido2.so.1.

ci: install packages needed to test upcoming dlopen features

---

man/dracut.usage.adoc

Attempt to clarify hostonly.
Original definition is from 2013 from this commit - b6c897681
Fixes #

man(usage): clarify hostonly

---

.github/workflows/integration.yml

This test is only flaky on Fedora and it needs several times to retry on each PR.
Let's disable it and let the Fedora team investigate it.
Filed https://github.com/dracut-ng/dracut-ng/issues/1284 to reenable.

ci(fedora): test 61 (MULTINIC) is failing on Fedora

---

modules.d/01systemd-cryptsetup/module-setup.sh
modules.d/90btrfs/module-setup.sh
modules.d/90crypt/module-setup.sh
modules.d/90dmraid/module-setup.sh
modules.d/90kernel-modules/module-setup.sh
modules.d/90lvm/module-setup.sh
modules.d/90mdraid/module-setup.sh
modules.d/90multipath/module-setup.sh
modules.d/90qemu-net/module-setup.sh
modules.d/90qemu/module-setup.sh
modules.d/95cifs/module-setup.sh
modules.d/95fcoe-uefi/module-setup.sh
modules.d/95fcoe/module-setup.sh
modules.d/95iscsi/module-setup.sh
modules.d/95lunmask/module-setup.sh
modules.d/95nbd/module-setup.sh
modules.d/95nfs/module-setup.sh
modules.d/95nvmf/module-setup.sh
modules.d/95virtiofs/module-setup.sh
modules.d/99fs-lib/module-setup.sh

Sloppy mode is the original hostonly mode.
Strict mode was newly introduced much later in 2018 ([v048](https://github.com/dracut-ng/dracut-ng/blob/main/NEWS.md#dracut-048)) as a non-default opt-in special optimization mode to allow modules to ignore more drivers or do some extra job to save memory and disk space, while making the image less portable.
This PR includes more dracut modules (and with that more kernel modules) in sloppy mode.
Fixes #

fix: improve hostonly sloppy mode

---

dracut-init.sh

Introduce logic to remove unlikely or impossible firmware on a platform- specific basis to save space - this is the largest set of firmware in the linux-firmware.git tree.
To update the list of prefixes:
1. Look for (grep) MODULE_FIRMWARE in /drivers/gpu/drm/amd (please note that AMD does not always use the file name to the firmware as parameter to this macro.
2. Reference "Misc AMDGPU driver information"[^1], Wikipedia, and TechPowerUp to determine which class certain set(s) of firmware belong out of the list below.
3. Refer to manufacturers and/or OEM contacts for state of support (some should be obvious - there is no non-x86 APUs - yet?).
[^1]: https://docs.kernel.org/gpu/amdgpu/driver-misc.html

dracut-init: strip out unused/unlikely AMDGPU firmware

---

test/container/Dockerfile-opensuse

As the the strict and non-strict (a.k.a. sloppy) hostonly configurations are significantly different, the CI should have test covergae for both.
Enable strict hostonly for the openSUSE container.
Fixes #

ci(opensuse): enable strict hostonly

---

dracut.sh

In drivers/add_drivers/force_drivers/omit_drivers kernel modules lists replace all occurrences of "-" with "_", not only the first one!
[x ] I have tested it locally
[ x] I have reviewed and updated any documentation if relevant
The issue that kernel modules in drivers/add_drivers/force_drivers/omit_drivers modules lists with "-" in their name are ignored except the first module with only one "-" in its name.

fix(dracut): kernel module name normalization in drivers lists

---

test/TEST-41-FULL-SYSTEMD/test.sh
test/container/Dockerfile-azurelinux

TEST-41 is failing on azurelinux due to issues with multipath and systemd-portabled dracut modules.
Since this test is passing on many other Linux environments already, this is unlikely an issue with dracut or with the test suite.
Remove binaries to prevent multipath and systemd-portabled dracut modules to be tested until the issues are resolved with the azurelinux container.
CC @trungams 
The failures can be observed at this GH Action - https://github.com/dracut-ng/dracut-ng/actions/workflows/integration-extra.yml
Fixes #

ci(azurelinux): remove some binaries to workaround test failures

---

test/container/Dockerfile-debian

NFS test requires url-lib dracut module (and curl).
CC @bdrung @LaszloGombos

test(debian): enable url-lib dracut module testing

---

man/dracut.usage.adoc

Seems this documentation bug was there from the very beginning - see 2d9f5858b
Fixes #957

fix(man): --include can be specified multiple times

---

modules.d/99base/init.sh

This PR only impacts non-systemd based initramfs.
Inspired by https://salsa.debian.org/kernel-team/initramfs-tools/-/commit/319cdc98f15d3213f58610141a84b5c67a8a1ebc
Fixes #

fix(base): tighten /dev/pts permissions

---

modules.d/06rngd/module-setup.sh

As confirmed by the original author: @rmetrich `Renaud Métrich <rmetrich@redhat.com>` in https://github.com/dracut-ng/dracut-ng/issues/1286
This file was originally licensed under GPL-3+ but that was not intentional, instead relicense it under GPL-2+ to match the project license.
Change license of  `modules.d/06rngd/module-setup.sh`
Fixes #1286

fix(rngd): adjust license to match the license of the whole project

---

modules.d/95squash-erofs/module-setup.sh

- `-C 65536` should be specified to match the default setup `-b 131072` for SquashFS;
- `-x -1` should be specified to match the SquashFS `-no-xattrs`;
- `-U 00000000-0000-0000-0000-000000000000` for reproducibility;
- `-T 0` can be specified to clear all inode timestamps for reduced metadata since I'm not sure timestamps are needed for dracut.
Fixes #

fix(squash-erofs): fix configuration in order to match SquashFS

---

test/TEST-30-DMSQUASH/test.sh

In some distributions (e.g. Alpine), ext4 and squashfs might not be loaded as it might not be built into the Linux kernel.
Fixes #

test(DMSQUASH): make sure ext4 and squashfs kernel modules are loaded

---

AUTHORS
NEWS.md
dracut-version.sh

Release 107 marks the one-year anniversary of this project.                                                                                                                                                                          
To celebrate the anniversary, the project would like to thank the following Linux distributions that rely on this project for initramfs generation.                                                                                   
* Adélie Linux                                                                                                                                                                                                                        
* ALT Linux …

docs: update NEWS.md and AUTHORS for release 107

---

modules.d/01systemd-cryptsetup/module-setup.sh

These modules have some large dependencies. Allow users to explicitly omit them if desired. Other modules like systemd-udevd also do this.

fix(systemd-cryptsetup): don't pull in fido2/pkcs11/tpm2-tss if omitted

---

modules.d/45simpledrm/module-setup.sh

On Qualcomm CRD the display only turns on after the initrd. The initrd seems to be missing the panel module.
So install `=drivers/gpu/drm/panel` on ARM also in the simpledrm module (similar to the drm module).
Bug-Ubuntu: https://launchpad.net/bugs/2107477

fix(simpledrm): add =drivers/gpu/drm/panel on ARM

---

modules.d/91crypt-gpg/README
modules.d/91crypt-gpg/crypt-gpg-lib.sh
modules.d/91crypt-gpg/module-setup.sh

This pull request changes crypt-gpg, allows it to import multiple pubkeys that match `crypt-public-key*.gpg` instead of importing only `crypt-public-key.gpg`. This way a keyfile can be decrypted by multiple recipients thus allowing for backups or for multiple users.
At install, all keys matching `crypt-public-key*.gpg` are found with `find` and copied.
At boot, these are listed with `ls` by glob matching and later imported
Fixes #1246

Feat(crypt-gpg): handle multiple gpg pubkeys

---

Makefile
configure
dracut-functions.sh
dracut-init.sh
dracut.sh
man/dracut.8.adoc
man/dracut.conf.5.adoc
modules.d/00systemd/module-setup.sh
modules.d/01systemd-bsod/module-setup.sh
modules.d/01systemd-coredump/module-setup.sh
modules.d/01systemd-integritysetup/module-setup.sh
modules.d/01systemd-journald/module-setup.sh
modules.d/01systemd-veritysetup/module-setup.sh
modules.d/91crypt-gpg/module-setup.sh
src/install/dracut-install.c
test/TEST-40-SYSTEMD/test.sh
test/dracut.conf.d/test/test.conf

Brace yourselves, it's a big one. :sweat_smile: I will summarise here. Further details are in the commit messages and code comments.
As suggested in #154, this checks ELF headers for `.note.dlopen` entries that state which libraries may be `dlopen`ed by the binary. At this time, only systemd uses this convention.
This metadata is in JSON format, so also as suggested, this makes use of libsystemd's newly exposed sd-json API. If libsystemd is too old or not present at all, then this dlopen handling is simply skipped.
Unconditionally installing all such dlopen dependencies would probably result in larger images rather than smaller ones, so modules can express which features they need through `add_dlopen_features`, and users can append to this too. Conversely, users can opt out of features …

Parse ELF .note.dlopen entries for dependencies, replace ldd for better cross support

---

test/TEST-10-BASIC/test.sh
test/TEST-13-SYSROOT/test.sh
test/TEST-20-STORAGE/create-root.sh
test/TEST-23-IMSM/create-root.sh
test/TEST-26-ENC-RAID-LVM/create-root.sh
test/TEST-30-DMSQUASH/test.sh
test/TEST-43-KERNEL-INSTALL/test.sh
test/TEST-60-NFS/client-init.sh
test/TEST-60-NFS/create-root.sh
test/TEST-61-MULTINIC/client-init.sh
test/TEST-61-MULTINIC/create-root.sh
test/TEST-62-BONDBRIDGEVLAN/create-root.sh
test/TEST-70-ISCSI/client-init.sh
test/TEST-70-ISCSI/create-client-root.sh
test/TEST-71-ISCSI-MULTI/client-init.sh
test/TEST-71-ISCSI-MULTI/create-client-root.sh
test/TEST-72-NBD/client-init.sh
test/TEST-72-NBD/create-encrypted-root.sh
test/TEST-72-NBD/create-server-root.sh
test/test-functions

The tests call `sync` without any parameters. This slows down the tests in case some unrelated disk writes happen somewhere else.
Specify the relevant files that should be synchronized to avoid unrelated writes to slow down the tests.

test: sync only relevant files

---

dracut-functions.sh

Currently check_vol_slaves_all return 0 even after checks on all slaves fail. And this leads to an issue that "dracut -hostonly-mode strict" gets stuck forever because instmods keeps waiting for user input when it's passed empty argument in the kernel-modules module.
Fixes: c7c8c498 ("dracut-functions.sh: catch all lvm slaves")
Reported-by: Tomáš Bžatek <tbzatek@redhat.com>

fix(dracut-functions.sh): let check_vol_slaves_all return 1 when checks on all slaves fail

---

dracut-init.sh

Initialize the local variable `_files` in `inst_libdir_file` to make the function work with `set -u`.
Fixes #

fix(dracut-init.sh): initialize _files in inst_libdir_file

---

dracut-init.sh

Support `DRACUT_NO_XATTR` being unset when using `set -u`.
Fixes #

fix(dracut-init.sh): support DRACUT_NO_XATTR being unset

---

dracut-init.sh
dracut.sh

Support `DRACUT_RESOLVE_LAZY` being unset when using `set -u`.
Fixes #

fix: support DRACUT_RESOLVE_LAZY being unset

---

test/test-functions

Initialize the optional variables in `bootindex` to make the function work with `set -u`.
Fixes #

test: initialize bootindex in qemu_add_drive

---

dracut-logger.sh

Initialize the local variable `errmsg` in `dlog_init` to make the function work with `set -u`.
Fixes #

fix(dracut-logger.sh): initialize errmsg in dlog_init

---

test/TEST-41-FULL-SYSTEMD/test.sh
test/TEST-60-NFS/test.sh
test/TEST-61-MULTINIC/test.sh
test/TEST-62-BONDBRIDGEVLAN/test.sh
test/TEST-70-ISCSI/test.sh
test/TEST-71-ISCSI-MULTI/test.sh
test/TEST-72-NBD/test.sh
test/TEST-81-SKIPCPIO/test.sh
test/TEST-82-DRACUT-CPIO/test.sh
test/modules.d/70test-root/module-setup.sh
test/test-container.sh
test/test-functions

Support following environment variables to be unset (to support `set -u` in the future):
* SERIAL
* SERVER_DEBUG
* DEBUGOUT
* CPIO_TESTDIR
* V
Fixes #

test: support some environment variables to be unset

---

.github/workflows/pr.yml

@master seems to report the folloeing error                                                                                                                                                                                           
Error: Resource not accessible by integration                                                                                                                                                                                         
Switch to @v3, as it is the last stable version.

chore: version lock commisery-action

---

test/TEST-80-GETARG/test.sh

Set `NEWROOT` to an existing directory to make sourcing `dracut-lib.sh` work with `set -u`.
Fixes #

test(GETARGS): initialize NEWROOT for dracut-lib.sh

---

modules.d/35network-manager/module-setup.sh

network-manager does not require dbus to function when using the `--configure-and-quit=initrd` option. This should be guaranteed as it is documented behavior in the [NetworkManager.conf(5) manpage](https://man.archlinux.org/man/extra/networkmanager/NetworkManager.conf.5.en) and specifically mentions dracut's use case.
With this change, initramfs images that don't or can't use systemd can use network-manager instead of the old network-legacy module.
- Tested with zfsbootmenu (no systemd) and Fedora (with systemd), both built from a Fedora 42 host
- I don't believe there are any docs to update
Fixes: #1422

fix(network-manager): depend on dbus only when using systemd

---

dracut-init.sh

This reverts commit 81ddde54051351ea17dbb84ef6232820f96740af. dracut itself may not use inst_library, but external modules do, at least anaconda's does.
Fixes #1435

Revert "chore: remove unused function"

---

src/install/dracut-install.c

Calling `dracut-install --modalias` will print kernel modules in an unstable order. This breaks reproducible builds, because the output is stored inside the initrd as `lib/dracut/hostonly-kernel-modules.txt`.
So sort the output of `--modalias` to be reproducible and easier to diff.
Partially fixes https://github.com/dracut-ng/dracut-ng/issues/1409

fix(dracut-install): sort output of --modalias

---

test/container/Dockerfile-void

Previously dracut network-manager package only worked with systemd. Now after 58baf86, network-manager dracut package should work in non-systemd Linux distributions as well, such as Void Linux.
Install NetworkManager into the Void CI container to enable testing it on the CI.
CC @classabbyamp

ci: install NetworkManager into the Void CI container

---

modules.d/70dmsquash-live/dmsquash-live-root.sh

This PR fixes the issue that recent kernels can mount EROFS directly without loop devices, and this feature is enabled in Fedora kernels (>=6.12; CONFIG_EROFS_FS_BACKED_BY_FILE=y). This feature is now supported by mount/libmount, too.
I think the best approach would be to avoid the second mount altogether, independently of the util-linux version.
It is more robust to use a bind mount there than to attempt to create a second instance of the same file system.
Fixes #1384
CC @FGrose @karelzak

fix(dmsquash-live): erofs collision with latest util-linux

---

dracut-functions.sh
dracut.sh

This reverts commit eab9b75c8a9b ("dracut.sh: add DRACUT_PATH").
Drop `DRACUT_PATH` and rely on `PATH` instead to avoid user confusion and behave like most other programs.
To avoid failing on misconfiguration (e.g. when `/usr/sbin` is not in `PATH`), ensure that the common default paths `/usr/sbin`, `/usr/bin`, `/sbin`, and `/bin` are included in `PATH`.
Fixes: https://github.com/dracut-ng/dracut-ng/issues/1467

feat(dracut): drop DRACUT_PATH and rely on PATH

---

modules.d/80base/module-setup.sh
test/TEST-13-SYSROOT/test.sh

Replace `sed` with `grep` and simplify logic by removing a conditional and if needed simply copying the line from the host shadow file to the initramfs shadow file.
Add test coverage for root entry in /etc/shadow. 
Fixes #1478

fix(base): base module failure if root password is already set

---

dracut-initramfs-restore.sh

In case no initrd was found for the kernel version, also check the the symlinks `/boot/initrd.img` (for Ubuntu) and `/initrd.img` (for Debian).
Fixes #

fix(dracut-initramfs-restore): check for Debian initrd.img symlink

---

dracut.sh

feat(dracut.sh): output error message for --regenerate-all
Without it, users might be confused on which initrd is failing.
Fixes #

feat(dracut.sh): output error message for --regenerate-all

---

src/install/dracut-install.c

This fixes the following in dracut-install:
* The -n short option for --dry-run
* RUNPATH expansion returning empty strings
* [The handling of absolute paths in sonames](https://bugs.gentoo.org/961101)

Various dracut-install ELF parsing fixes

---

Makefile

The `cp` command will copy the file/directory permissions from the source files. The local source files might have group write permission set which should not be applied to the installation.
Tighten the file/directory permission by using the `install` command with specifying the mode.
Please review and merge https://github.com/dracut-ng/dracut-ng/pull/1521 first.
Fixes #

fix(Makefile): use install for installing files

---

src/install/dracut-install.c

Calling `mmap` with 0 length results in an invalid argument error, so check the length first.
Fixes: https://bugs.gentoo.org/961340

fix(dracut-install): broken calls to mmap with 0 length

---

modules.d/35network-legacy/module-setup.sh
modules.d/35network-manager/module-setup.sh
modules.d/45net-lib/module-setup.sh
test/TEST-50-NETWORK/test.sh

For static IPv4 configurations, we use arping to check for duplicate IP addresses. arping requires the af_packet module to work, and if arping fails, the IP address will not be set and booting will fail. af_packet may not be loaded / required in the running system, for example if the system had been booted in an IPv6 configuration, or if it had been manually unloaded. Make sure it's included in initramfs in hostonly mode, too.
network-manager always requires nf_tables and other kernel modules in the generated initramfs to function, regardless if these modules are loaded on the host or not at the time of initramfs generation.
Remove the hostonly_mode=sloppy workaround. The NETWORK test now passes regardless of the value of `hostonly_mode`.      
Follow-up to b074216, 5e1fec168 and to …

fix: always include modules required for networking

---

test/container/Dockerfile-gentoo

network-manager dracut module no longer depends on the systemd dracut module. 
Alpine and Void CI containers have switched over to networkmanager networking already. 
Let's install networkmanager into the Gentoo CI container as well.
Fixes #1609

ci(gentoo): install networkmanager when systemd is not installed

---

dracut-logger.sh
lsinitrd.sh
modules.d/30convertfs/convertfs.sh
modules.d/70dm/dm-shutdown.sh
modules.d/70kernel-modules/module-setup.sh
modules.d/70mdraid/md-shutdown.sh
modules.d/70multipath/module-setup.sh
modules.d/74fcoe-uefi/module-setup.sh
modules.d/74fcoe/module-setup.sh
modules.d/74iscsi/module-setup.sh
modules.d/74lunmask/module-setup.sh
modules.d/74nvmf/module-setup.sh
test/TEST-80-GETARG/test.sh

Shellcheck 0.11 complains about SC2268 (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
Shellcheck <= 0.10 complains about SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly). Shellcheck 0.11 changes this complaint to SC2329 (info): This function is never invoked. Check usage (or ignored if invoked indirectly).
So ignore shellcheck SC2329 in addition to SC2317 to make both shellcheck versions happy.
Fixes #

fix: support shellcheck 0.11

---

modules.d/11systemd-cryptsetup/module-setup.sh
modules.d/70btrfs/module-setup.sh
modules.d/70crypt/module-setup.sh
modules.d/70dmraid/module-setup.sh
modules.d/70lvm/module-setup.sh
modules.d/70mdraid/module-setup.sh
modules.d/70multipath/module-setup.sh
modules.d/70qemu-net/module-setup.sh
modules.d/70qemu/module-setup.sh
modules.d/74cifs/module-setup.sh
modules.d/74fcoe-uefi/module-setup.sh
modules.d/74fcoe/module-setup.sh
modules.d/74hwdb/module-setup.sh
modules.d/74iscsi/module-setup.sh
modules.d/74lunmask/module-setup.sh
modules.d/74nbd/module-setup.sh
modules.d/74nfs/module-setup.sh
modules.d/74nvmf/module-setup.sh
modules.d/74virtiofs/module-setup.sh

This commit is a _partial_ revert of 8519dcd.
The goal of this commit is to have the same dracut modules included in both `sloppy` and in `strict` mode, but the dracut modules themselves might install more kernel modules depending on the `hostonly_mode` value.
Changes in other areas of the code (e.g. changes inside `installkernel`) were not reverted as they require more discussions and agreement by the community.
As an example the `crypt` dracut module could potentially copy more kernel modules into the generated initramfs in `sloppy` `hostonly_mode` mode than in `strict` `hostonly` mode.
CC @pvalena @AdamWill @lnykryn @Conan-Kudo
Related issue https://github.com/dracut-ng/dracut-ng/issues/748

fix: partial revert for hostonly sloppy mode

---

test/container/Dockerfile-debian

Now, that the CI transitioned to Debian trixie release let's remove Debian workarounds for kernel-install.
This commit is a revert for 64d6da9f2 .
Fixes #

ci(debian): revert Debian workarounds

---

test/container/Dockerfile-debian

Install all package dependencies based on downstream packaging.
This commit ensures that we do not miss some dowsntream package dependencies here upstream.
Fixes #

ci(debian): install packages recommended by packaging

---

test/TEST-11-USR-MOUNT/create-root.sh
test/TEST-11-USR-MOUNT/test.sh

Add a step to create a read-only btrfs snapshot and mount it.
Fixes #

test(USR-MOUNT): add a test step to mount read-only btrfs snapshot

---

test/TEST-12-UEFI/test.sh
test/TEST-43-KERNEL-INSTALL/test.sh

Including workaround in the test case itself will allow to pass it downstream.
These workarounds are still needed.
Fixes #

ci(debian): move workaround to the test case

---

test/TEST-41-FULL-SYSTEMD/test.sh

Test FULL `systemd` without the `dbus` dracut module.
This is a follow-up to fdfa899.
Fixes #

tests(FULL-SYSTEMD): remove dbus dependency

---

test/TEST-81-SKIPCPIO/test.sh

Support using 3cpio in the skipcpio test to allow not having `cpio` installed.
Fixes #

test(SKIPCPIO): support 3cpio

---

modules.d/16dbus-broker/module-setup.sh
modules.d/16dbus-daemon/module-setup.sh
modules.d/35network-manager/module-setup.sh

Files under /etc on the host are considered host specific. Do not include them in the generic initramfs.
As an example `$dbussystemconfdir/teamd.conf` points to `/etc/dbus-1/system.d/teamd.conf` - which should be only included in hostonly initramfs.
Fixes #

fix(dbus, network-manager): make generic mode host independent

---

modules.d/74iscsi/module-setup.sh

Files under /etc on the host are considered host specific. Do not include them in the generic initramfs.
Fixes #

fix(iscsi): do not include /etc/iscsi/iscsid.conf in generic mode

---

modules.d/45plymouth/module-setup.sh

The only Bash script in the Plymouth module is
`plymouth-populate-initrd.sh` which is called by `module-setup.sh` and not included in the initrd. Therefore the Plymouth module does not require Bash.
Fixes: 3a04a139700 ("fix: add bash dependency when bash scripts are used in the module")
@jozzsi This reverts https://github.com/dracut-ng/dracut-ng/pull/925 partially.
Fixes #

fix(plymouth): drop depending on bash

---

dracut.conf.d/opensuse/01-dist.conf
dracut.sh
man/dracut.conf.5.adoc
shell-completion/bash/dracut

Extend the Dracut configuration to configure the default compression level for each compression format (e. g. `compress_level_zstd` for zstd). Add `--compress-level` option to `dracut` to override the compression level from the configuration.
Then users could just call `dracut --zstd --compress-level 3` instead of `dracut --compress="zstd -3 -T0 -q"`.
Fixes #

feat(dracut): support setting compression level separately

---

modules.d/45plymouth/module-setup.sh

On amd64 `dpkg-architecture -qDEB_HOST_MULTIARCH` returns `x86_64-linux-gnu` but `uname -m` returns only `x86_64`. `/usr/lib/x86_64` does not exist on Debian/Ubuntu but `/usr/lib/x86_64-linux-gnu` exists.
Rely on `libdirs` to provide all possible library directories including the Debian multiarch directory `/usr/lib/x86_64-linux-gnu`.
Fixes: 1b374931126c ("fix(plymouth): do not depend on dpkg-architecture")

fix(plymouth): check all library directories for Plymouth

---

modules.d/45plymouth/module-setup.sh

The script `plymouth-set-default-theme` is not needed inside the initrd, because it is not called by anything. So skip installing it.
Fixes #

fix(plymouth): do not install plymouth-set-default-theme into initrd

---

dracut.sh
man/dracut.conf.5.adoc
test/TEST-12-UEFI/test.sh

Allow dracut read configuration files from /run as well, in addition to /etc/ and /usr.
Modify test case to demonstrate use-case and provide test coverage.
Fixes #

feat(dracut): add support for /run/initramfs/dracut.conf.d
