dracut-ng/dracut-ng

.github/workflows/codeql.yml
.github/workflows/container.yml
.github/workflows/integration.yml
.github/workflows/lint.yml
docs/RELEASE.md
tools/release.sh

Changed the default branch name from master to main.

chore: rename master to main

---

modules.d/90livenet/livenetroot.sh

Some fixes related to getting live image size.
(Cherry-picked commit from dracutdevs/dracut#2611)

fix(livenet): some fixes related to getting live image size

---

modules.d/95resume/module-setup.sh

The grep introduced in commit e3a7112bef794e2f2dd741ec2c74fa9cb9117651 does not work as intended. The resume module is always excluded in hostonly mode.
Made this a bit more explicit with if/else so it is more clear what is going on. The in-line ||/&& makes the line really long and makes it more difficult to understand what is going on.
Bug: https://github.com/dracutdevs/dracut/issues/924
(Cherry-picked commit from dracutdevs/dracut#2494)

fix(resume): include in hostonly mode if resume= on cmdline

---

src/install/dracut-install.c

Resolves https://github.com/dracut-ng/dracut-ng/security/code-scanning/3
(Cherry-picked commit from dracutdevs/dracut#2231)
Received positive feedback from @tobhe

fix(dracut-install): file created without restricting permissions

---

.github/workflows/codeql.yml

Only run scanner if src/ directory changed
(Cherry-picked commit from dracutdevs/dracut#2230)
Positive feedback from @aafeijoo-suse @mrc0mmand

ci: only run C code scan if src/ directory changed

---

Makefile

Remove dist make target as it is no longer used or maintained.
(Cherry-picked commit from dracutdevs/dracut#2504)
Positive feedback from @pvalena

fix(Makefile): release is now just made out of a git sha

---

docs/RELEASE.md
tools/release.sh

fix(release): dracutdevs/dracut --> dracut-ng/dracut-ng

---

test/container/Dockerfile-Arch
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-OpenSuse-latest

Prefer command over which and keep it that way.
Follow-up to https://github.com/dracutdevs/dracut/pull/2393 . 
Small win, but still a win :-)

ci: drop which package from CI containers

---

test/TEST-11-LVM/finished-false.sh
test/TEST-11-LVM/hard-off.sh
test/TEST-11-LVM/test.sh

First commit from https://github.com/dracutdevs/dracut/pull/2260 . 
Reference https://github.com/dracutdevs/dracut/pull/2260/commits/c2dea6bbb50e85f497b91649672caf44831af1d5
I plan to split this PR, so that each commit is its own PR to help with the reviews and to help manage the complexity.

test(LVM): make test 11 use the test dracut modules

---

.github/workflows/release.yml
.gitignore
dracut.html
tools/release.sh

Plan to update dracut.html as part of release generation together with [dracut-version](https://github.com/dracut-ng/dracut-ng/blob/main/dracut-version.sh ).
Fixes https://github.com/dracut-ng/dracut-ng/issues/103
CC @pvalena

fix(release): maintain dracut.html in the source tree

---

tools/release.sh

This change was manually done earlier at release generation. This PR corrects the automated script.

fix(release): dracut --> dracut-ng for NEWS.md

---

README.md

docs(README.md): repology badges

---

.github/workflows/container.yml

Enable testing on arm64 using the Debian container.

ci: enable testing on arm64 

---

test/container/Dockerfile-Gentoo

fix(test): add support for thin volumes in the Gentoo container

---

.github/workflows/integration.yml
test/run-qemu
tools/test-github.sh

This is an easy test to start with as it does not require a VM.
Only set CPU to IvyBridge-v2 for AMD64.

ci: run GETARG test on arm64

---

.github/workflows/integration.yml

ci: make checkout faster and fix concurrency rules

---

test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-Ubuntu
test/container/Dockerfile-alpine

Enabled to test dracut-cpio on all CI Linux distribution.

ci: install rust into each CI container

---

test/TEST-13-ENC-RAID-LVM/create-root.sh
test/TEST-13-ENC-RAID-LVM/test-init.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-17-LVM-THIN/create-root.sh
test/TEST-17-LVM-THIN/test-init.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-20-NFS/client-init.sh
test/TEST-20-NFS/create-root.sh
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/client-init.sh
test/TEST-30-ISCSI/create-client-root.sh
test/TEST-30-ISCSI/create-server-root.sh
test/TEST-30-ISCSI/server-init.sh
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/client-init.sh
test/TEST-35-ISCSI-MULTI/create-client-root.sh
test/TEST-35-ISCSI-MULTI/create-server-root.sh
test/TEST-35-ISCSI-MULTI/server-init.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/client-init.sh
test/TEST-40-NBD/create-client-root.sh
test/TEST-40-NBD/create-encrypted-root.sh
test/TEST-40-NBD/create-server-root.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/client-init.sh
test/TEST-50-MULTINIC/create-root.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/create-root.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/test-functions

test: switch to virtio for the QEMU drive

---

modules.d/01systemd-journald/module-setup.sh

fix(systemd-journald): add systemd dependency

---

modules.d/90crypt/module-setup.sh

fix(crypt): add systemd-ask-password dependency if systemd is used

---

modules.d/01systemd-initrd/module-setup.sh

fix(systemd-initrd): only include it if another module depends on it

---

modules.d/98dracut-systemd/dracut-emergency.sh
modules.d/99base/dracut-lib.sh

Be consistent and always perform the actual action you would expect from the name.

fix(dracut-init.sh): force to perform the actual action

---

.github/workflows/integration.yml

ci: add Fedora on arm64 to the integration tests

---

test/container/Dockerfile-Void

The newly added packages are all present in the Arch container.

ci: add more packages to the Void container to enable more testing

---

modules.d/80test/module-setup.sh
test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-18-UEFI/test.sh
test/TEST-20-NFS/test.sh
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/TEST-63-DRACUT-CPIO/test.sh
test/test-functions

This PR makes is easier to spot inconsistencies between tests by having the common part of the tests in a single place in `test-functions`.

test: update all tests to build initrd with test_dracut

---

modules.d/00systemd/module-setup.sh

Follow-up improvement after https://github.com/dracut-ng/dracut-ng/pull/246
Since systemd-initrd module depends on systemd-journald and systemd-tmpfiles directly, they will be always pulled in by systemd-initrd module, so it should not be repeated by the systemd module.

perf(systemd): remove duplicate rules

---

modules.d/01systemd-ask-password/module-setup.sh

Follow-up to 6c5520dff67a63df4ee735ab4f618d3faaf869d9

fix(systemd-ask-password): resolve regression

---

configure

Resolve regression after https://github.com/dracutdevs/dracut/pull/2580
From https://github.com/OpenMandrivaAssociation/dracut/commit/f1020895de807decd54fda745bfcef3de89a1fb8

fix(configure): resolve regression for crosscompiling

---

test/TEST-01-BASIC/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-20-NFS/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/test.sh
test/TEST-63-DRACUT-CPIO/test.sh
test/run-qemu

Add it to the function instead of all the call sites in all tests. Less code and more consistent.

tests: configure watchdog-action in run-qemu

---

modules.d/01systemd-ldconfig/module-setup.sh
test/TEST-04-FULL-SYSTEMD/test.sh

I saw the ping on #312, so just forwarding my patch from Ubuntu.
Install ldconfig.real in 01systemd-ldconfig.  
Fixes #312

fix(01systemd-ldconfig): install ldconfig.real

---

modules.d/90dm/dm-shutdown.sh

This is an alternative implementation of https://github.com/dracutdevs/dracut/pull/2471. Instead of using a separate module, let's do this in the `90dm` module, which already has a shutdown script used to remove device mappers. Using deferred removal seems a little hacky to me and I'm worried about race conditions that may arise between the deferring mechanism and the `90dm` module. Imagine this: you have a dm-crypt device and on top of that you have an LVM. If we schedule deferred removal of the dm-crypt device, it won't happen right away, because the LVM is still holding it. So we walk through all the shutdown scripts until we get to `90dm`. We use `dmsetup remove` to deactivate the LVM and now the dm-crypt no longer has any holders, so it's free to be removed. But there is a problem - …

feat(90dm): close crypt devices using cryptsetup

---

test/container/Dockerfile-Arch
test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-Gentoo
test/container/Dockerfile-OpenSuse-latest
test/container/Dockerfile-Ubuntu
test/container/Dockerfile-Void

This is in preparation for increasing the test coverage for UKI generation.

ci: add sbsigntool and ukify to test containers

---

AUTHORS
NEWS.md
dracut-version.sh
dracut.html

docs: update NEWS.md and AUTHORS

---

modules.d/01systemd-networkd/module-setup.sh

fix(systemd-networkd): this module depends on systemd

---

modules.d/90crypt/parse-crypt.sh

fix(crypt): decryption when rd.luks.name is set

---

dracut-init.sh
modules.d/90mdraid/59-persistent-storage-md.rules
modules.d/90mdraid/parse-md.sh
modules.d/95resume/parse-resume.sh

refactor: replace long-time deprecated $tempnode with $devnode

---

dracut.sh
man/dracut.8.asc
man/dracut.conf.5.asc

> Despite its name, this command only sets initrd parameters.
Fixes #400

fix(man): clarify semantics for --kernel-cmdline

---

modules.d/90mdraid/mdraid_start.sh

If some raid devices with specified UUIDs fail to be assembled in initrd, we will try to assemble them again in this script to avoid system falling into emergency mode. This patch is created because we can offen see mdadm command failure during boot because of timing issue introduced between mdadm and udevd.
Fixes #

fix(mdraid): try to assemble the missing raid device

---

dracut.conf.d/50-fips.conf
dracut.conf.d/50-generic.conf
dracut.conf.d/50-hostonly.conf
dracut.conf.d/50-rescue.conf

This PR makes it easier and consistent to package common configurations for distribution.

feat: add additional common configs

---

NEWS.md
docs/BASH.md
docs/README.kernel
dracut.conf.d/suse.conf.example
man/dracut-catimages.8.asc
man/dracut.asc
man/dracut.conf.5.asc
man/dracut.usage.asc
test/Makefile
tools/profile.py

Remove trailing newlines from all files in the repository.

chore: remove trailing newlines

---

test/run-qemu

test: virtual hardware watchdog not available on s390x

---

.github/workflows/integration.yml

ci: run systemd-networkd tests on Ubuntu as well

---

test/TEST-20-NFS/hosts
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/hosts
test/TEST-30-ISCSI/test.sh
test/TEST-35-ISCSI-MULTI/hosts
test/TEST-35-ISCSI-MULTI/test.sh
test/TEST-40-NBD/hosts
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/hosts
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLAN/hosts
test/TEST-60-BONDBRIDGEVLAN/test.sh

CI uses IP addresses for simplicity.
I was considering actually using them instead of deleting them, but that would just introduce another source for potential new issues.

test: delete hosts files that are not used by tests

---

.github/workflows/integration.yml

ci: run extended tests on Alpine and Void as well

---

modules.d/95debug/module-setup.sh
test/TEST-04-FULL-SYSTEMD/test.sh

feat(debug): add findmnt to help debugging

---

src/install/dracut-install.c

To handle fw_devlink suppliers as dependencies, we traverse every device in /sys and collect a hashmap of module names to their suppliers before starting module installation work. The module names are found by reading and passing the "modalias" file to the `kmod_module_new_from_lookup()` function from libkmod. This function is unexpectedly slow on ARM64 systems with device-tree where this work is primarily necessary.
Usually (but not always), the running kernel has already looked up the modalias and bound a driver from the associated module. Get module names by resolving the "driver/module" symbolic link and taking its basename. If it doesn't exist, fall back to looking up the modalias.
It's possible that multiple modules match the modalias, in which case others will be ignored in favor …

perf(dracut-install): use driver/module sysfs dirs for module name

---

.github/workflows/integration.yml
test/TEST-04-FULL-SYSTEMD/test.sh

- ci: run extended tests on openSUSE as well
- test(FULL-SYSTEM): make sure systemd-pcrphase can be installed

ci: improve test coverage

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

This adds support for rootfs compressed with erofs. Either as a plain erofs image or a LiveOS/rootfs.img ext4 filesystem compressed with erofs.
This patch does not make any attempt to change the squashfs directory naming (or variable names) in order to make these changes as small as possible and easy to review. It also does not make any attempt to support the multitude of available options other than what is needed by anaconda-dracut calling this script to setup the boot.iso root filesystem.
(which isn't to say it doesn't work, it just hasn't been tested and is outside the scope of this change).
Add support for erofs to dmsquash-live-root for use with this lorax PR - https://github.com/weldr/lorax/pull/1403
Fixes #

dmdquash-live-root: Add support for using erofs

---

test/container/Dockerfile-Arch
test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-OpenSuse-latest
test/container/Dockerfile-Ubuntu
test/container/Dockerfile-Void
test/container/Dockerfile-alpine

Add erofs-utils to all the containers for use in testing #496

feat(test): add erofs-utils to the containers

---

tools/release.sh

Small incremental fixes for the release process. Happy to bikeshed the commit message further if there is interest :-)
- Add new version commit number to the commit message. 
- Lock clog version to a version that is working well. 
- Allow clog to be installed in the user home as well.

fix(release): improve commit message

---

modules.d/90mdraid/module-setup.sh

cherry-pick from https://github.com/aafeijoo-suse/dracut-mini/commit/f0e14571fbfff49ef20c4dae67410b091a499b5f

chore: remove support for old mdadm versions

---

modules.d/03modsign/module-setup.sh
modules.d/03rescue/module-setup.sh
modules.d/10i18n/module-setup.sh
modules.d/50drm/module-setup.sh
modules.d/90dm/module-setup.sh
modules.d/90kernel-network-modules/module-setup.sh
modules.d/90nvdimm/module-setup.sh
modules.d/91zipl/module-setup.sh
modules.d/95dasd_mod/module-setup.sh
modules.d/95debug/module-setup.sh
modules.d/95lunmask/module-setup.sh
modules.d/95virtfs/module-setup.sh
modules.d/96securityfs/module-setup.sh
modules.d/97biosdevname/module-setup.sh
modules.d/97masterkey/module-setup.sh
modules.d/98selinux/module-setup.sh
modules.d/99fs-lib/module-setup.sh
modules.d/99img-lib/module-setup.sh

cherry-pick from https://github.com/aafeijoo-suse/dracut-mini/commit/16c33537752a504414492efff2ea832db90414fd

chore: remove empty check functions

---

test/TEST-16-DMSQUASH/create-root.sh
test/TEST-16-DMSQUASH/test.sh

Testing kernel module support only works reliably form a VM that is booted from the given Linux kernel version.

test: check for kernel module support from within the VM

---

dracut-init.sh

Follow-up to c95075e2c792cdb0e18aac6300ae8dc0dd6a6c1b (see https://github.com/dracutdevs/dracut/pull/2104).

chore!: drop support for prepare_udev_rules

---

modules.d/90pcmcia/module-setup.sh

While the module itself is relativly new the technology is rarely used any more as part of the boot process.

feat(pcmcia): only include when another module requires it

---

test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-17-LVM-THIN/test.sh

Mark tests hostonly that are failing in no-hostonly mode
Fixes #

ci: mark tests no-hostonly that are failing in hostonly mode

---

modules.d/00systemd/module-setup.sh

fix(systemd): make nologin optional

---

test/TEST-02-SYSTEMD/test.sh

test(SYSTEMD): let dracut figure out to include systemd for this test

---

docs/HACKING.md
tools/test-podman.sh

Updated `HACKING.md` to point to the new test.sh script.
Fixes #

test(test.sh): script to run tests in podman 

---

test/TEST-14-IMSM/test.sh
test/container/Dockerfile-Debian

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056944
Fixes #

ci(Debian): remove dmraid in preparation for next Debian release

---

dracut.sh
man/dracut.conf.5.asc
modules.d/95rootfs-block/module-setup.sh
modules.d/95rootfs-block/mount-root.sh
modules.d/99fs-lib/fs-lib.sh
modules.d/99fs-lib/module-setup.sh

See https://github.com/torvalds/linux/blob/master/fs/reiserfs/Kconfig
Fixes #

chore(fs-lib): remove reiserfs support

---

test/container/Dockerfile-Gentoo

Closes: https://github.com/dracut-ng/dracut-ng/issues/630
Fixes #

fix(Dockerfile-Gentoo): explicitly pull in all build dependencies

---

modules.d/00bash/module-setup.sh
modules.d/00dash/module-setup.sh
modules.d/00systemd/module-setup.sh
modules.d/00warpclock/module-setup.sh
modules.d/01fips-crypto-policies/module-setup.sh
modules.d/01fips/module-setup.sh
modules.d/01systemd-ac-power/module-setup.sh
modules.d/01systemd-initrd/module-setup.sh
modules.d/01systemd-modules-load/module-setup.sh
modules.d/01systemd-repart/module-setup.sh
modules.d/01systemd-sysusers/module-setup.sh
modules.d/01systemd-tmpfiles/module-setup.sh
modules.d/04watchdog-modules/module-setup.sh
modules.d/35connman/module-setup.sh
modules.d/35network-manager/module-setup.sh
modules.d/90kernel-network-modules/module-setup.sh
modules.d/90ppcmac/module-setup.sh
modules.d/95dasd/module-setup.sh
modules.d/95rootfs-block/module-setup.sh
modules.d/95zfcp/module-setup.sh
modules.d/98dracut-systemd/module-setup.sh
modules.d/98pollcdrom/module-setup.sh
modules.d/98syslog/module-setup.sh
modules.d/99base/module-setup.sh
modules.d/99fs-lib/module-setup.sh
modules.d/99shutdown/module-setup.sh

It is not required to redefine empty functions.
Fixes #

chore: remove boilerplate

---

test/container/Dockerfile-Arch
test/container/Dockerfile-Debian
test/container/Dockerfile-Fedora-latest
test/container/Dockerfile-Gentoo
test/container/Dockerfile-Ubuntu
test/container/Dockerfile-Void
test/container/Dockerfile-alpine

This PR is just a container change, no tests are added or removed.
Fixes #

ci: add more fstypes support (xfs, jfs, f2fs)

---

modules.d/01fips-crypto-policies/module-setup.sh

fix(fips-crypto-policies): make it depend on fips dracut module

---

src/install/dracut-install.c

fix(dracut-install): use correct data type for pid

---

man/dracut.modules.7.asc

Document more creation functions for dracut modules.

docs: document more creation functions for dracut modules

---

man/dracut.8.asc

For context, this is the original commit for this feature: https://github.com/dracut-ng/dracut-ng/commit/1743473b2b7c1fb09b9eddc11d33fb3269877529
Fixes #

docs: clarify --print-cmdline

---

modules.d/40network/module-setup.sh

Add back testing the module with check_module as well as module_check.
Follow-up to c4b57722fb
Fixes #

fix(network): call both check_module and module_check

---

AUTHORS
NEWS.md
dracut-version.sh

docs: update NEWS.md and AUTHORS for release 106

---

.github/workflows/integration-extra-arm64.yml

These are arm64 runs not amd64 runs.

test: typo in the GitHub Action name

---

src/install/dracut-install.c

Call `install_firmware_fullpath` based on glob matched, compressed or uncompressed fwpath.
Fixes #1150

fix(dracut-install): install compressed blobs that match wildcard fwpath

---

modules.d/95nfs/module-setup.sh

nfs: some fixes

---

dracut.sh

Prefer to use ukify over the current objcopy and awk based solution to generate UKI.
Potentially fixes https://github.com/dracut-ng/dracut-ng/issues/215
Fixes #

feat(UKI): use ukify when available to generate UKI

---

test/TEST-60-NFS/test.sh

Use test-root and nfs dracut modules instead of reimplementing logic as part of the test case.

test(NFS): remove hardcoded dracut module ordering

---

test/TEST-80-GETARG/test.sh

The intention of this PR is to help with issue https://github.com/dracut-ng/dracut-ng/issues/538 and future-proof the test case.

test(GETARG): remove hardcoded dracut module ordering

---

doc_site/modules/ROOT/pages/modules/core.adoc
doc_site/modules/ROOT/pages/modules/systemd.adoc

document recently introduced dracut modules
- simpledrm
- systemd-battery-check
- systemd-emergency
Fixes #

chore: document recently introduced dracut modules

---

dracut-init.sh

fix(dracut-init): do not detect virt environment in non-hostonly mode

---

test/TEST-11-USR-MOUNT/test.sh
test/TEST-12-UEFI/test.sh

Follow-up to f698315 .
> In most cases the "--add-drivers" option is what you want to use.

test: change tests to recommended configuration

---

test/README.md

As discussed on July 14th in #1268, add a new and small test/README.md file for convenience. This is just a list of pointers/shortcuts to existing documentation. Add enough English around the pointers to make it easy to find the new location even if stuff moves. Even when pointers go out of date, it makes a big difference to have an idea of what you're looking for - and that it even exists in the first place!
- [N/A] I am providing new code and test(s) for it

docs(test): add new test/README.md

---

dracut.sh

The recent issues/pull request regarding reproducible builds triggered me to develop this one.
`SOURCE_DATE_EPOCH` is a standardised environment variable that distributions can set centrally and have build tools consume this in order to produce reproducible output (see https://reproducible-builds.org/docs/source-date-epoch/).
Enable reproducible builds when `SOURCE_DATE_EPOCH` is set and use this timestamp when clamping the mtime.

feat(dracut): support SOURCE_DATE_EPOCH

---

test/TEST-10-BASIC/test.sh
test/TEST-11-USR-MOUNT/test.sh
test/TEST-12-UEFI/test.sh
test/TEST-13-SYSROOT/test.sh
test/TEST-20-STORAGE/test.sh
test/TEST-26-ENC-RAID-LVM/test.sh
test/TEST-30-DMSQUASH/test.sh
test/TEST-40-SYSTEMD/test.sh
test/TEST-41-FULL-SYSTEMD/test.sh
test/TEST-42-SYSTEMD-INITRD/test.sh
test/TEST-43-KERNEL-INSTALL/test.sh
test/TEST-60-NFS/test.sh
test/TEST-61-MULTINIC/test.sh
test/TEST-62-BONDBRIDGEVLAN/test.sh
test/TEST-70-ISCSI/test.sh
test/TEST-71-ISCSI-MULTI/test.sh
test/TEST-72-NBD/test.sh
test/TEST-80-GETARG/test.sh
test/TEST-81-SKIPCPIO/test.sh
test/TEST-82-DRACUT-CPIO/test.sh

To make all tests more robust, use `set -u` in all tests.

test: use "set -u" in all tests

---

tools/release.sh

Document how to create release tag in `tools/release.sh`.
Fixes #

doc(release): document how to create release tag

---

dracut.sh

`3cpio` is written in Rust and faster than `cpio`. Use `3cpio` in `dracut.sh` in case it is available. `3cpio` supports `SOURCE_DATE_EPOCH` and therefore clamping the files is not needed.
With only cpio installed:
```
Benchmark 1: dracut -f
Time (mean ± σ):      6.700 s ±  0.052 s    [User: 8.724 s, System: 3.668 s]
Range (min … max):    6.646 s …  6.828 s    10 runs
```
With only 3cpio installed:
```
Benchmark 1: dracut -f
Time (mean ± σ):      6.606 s ±  0.033 s    [User: 8.737 s, System: 3.435 s]
Range (min … max):    6.552 s …  6.662 s    10 runs
```
Fixes #

feat(dracut): support 3cpio for creating initrds
